### ISSUE TITLE
Gateway Diagnostics

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-desktop#1140]
We could use IPFS Desktop to get some diagnostic data about the gateways with user's permission. That would allow us to get some info on why are is the gateway so slow at some times and really fast on others.

**Comment by hacdias** [comment]
@olizilla could you give me more info on this, please?

**Comment by SgtPooki** [comment]
Actually, I just noticed how old this is. I'm going to add to the other issue as is and close this.
