### ISSUE TITLE
Download multiple files issue

### ISSUE THREAD

**Issue by enOehTsIsihT** [ipfs/ipfs-desktop#1154]
- OS : win7 X64

- ipfs-desktop version : 0.9.3

After downloading multiple files, there is only one file in tar file.

**Comment by lidel** [comment]
@enOehTsIsihT is this still the case in the latest ipfs-desktop?

**Comment by enOehTsIsihT** [comment]
> @enOehTsIsihT is this still the case in the latest ipfs-desktop?

No,this is not still the case in the latest ipfs-desktop.
