### ISSUE TITLE
Support for Clusters

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-desktop#1159]
@olizilla suggested to add support for IPFS Cluster on IPFS Desktop. The main idea is to be able to form clusters with our friends and share our pins. In addition, that would allow us to give pins actual names for easier management.

IPFS Cluster should be embedded the same way as we already embed `go-ipfs`. Perhaps, initially, it could be hidden behind an experimental feature that could be enabled via the Web UI.

Some thoughts or questions left unanswered for now:

1. How to manage the pins? We already have a pins page under the Files section. Having both repo and cluster pins could be confusing. Certainly, we could figure out a better way to show them. Perhaps, on a single page, we could distinguish between Cluster and "only repo" pins by having a different icon, the name and some other indications.
2. Can an IPFS node be in multiple clusters? We would need multiple IPFS Cluster nodes running for that, correct? Is that reasonable?
3. Main functionality for end users? Create clusters with their friends? Manage their own pinning network?

For previous references, please see #602 and #622.

**Comment by SgtPooki** [comment]
I don't think we should do this in ipfs-desktop until we figure out how to decouple ipfs-webui from ipfs-desktop better so we have control over more of the UI components. Even then, I feel like instructing users to download a different binary that sets up clustering (or having kubo do this somehow) would be the right way forward for ipfs-desktop
