### ISSUE TITLE
[Feature Suggestion] - Auto complete hashes as they are being typed

### ISSUE THREAD

**Issue by otboss** [ipfs/ipfs-desktop#1278]
Lets say I want to share a hash to someone and the means is speech. They have to manually type out the entire hash in order to get the file. How about a feature where search field recommends files as the user types by listing hashes. At a certain length it is unlikely that the hash will be used for multiple files, saving time.

**Comment by hacdias** [comment]
As much as I appreciate the intent of this feature, this seems to be a really hard (if not impossible) thing to make. THere are all combinations of letters and digits in the hashes. 

In addition, we do not keep track of hashes in any way so it's not possible for us to autocomplete them accurately. The only thing that comes to my mind is to show all possible options, which are... lots of them.

**Comment by hacdias** [comment]
@autonome @lidel what do you think about this?

**Comment by lidel** [comment]
AFAIK we do not have/expose primitives for asking DHT, already connected peers or even local datastore for "all CIDs that start/end with `XYZ`". 

Described feature would require adding a new Core API that allows for that type of fuzzy lookup.

**Comment by ShadowJonathan** [comment]
IMO this does not sound like an problem that can be addressed via this solution of auto-completing hashes. It is nearly impossible to know what a user would want to type, as CIDs are an extremely dense format of nearly-straight-to-binary transformation.

Hashes, by their nature, are also meant to be non-reversible, and thus also non-guessable by extension. There exists millions upon millions of hashes out there on the network, knowing which one the user wants is what the user should provide, its not like google or netflix where the name is human-readable, and its often searched, and centrally tallied and re-distributed.

---

What I suggest instead as a solution is an extension to multibase, having a human-readable and speakable word list like [PGP does](https://en.wikipedia.org/wiki/PGP_word_list), that can be spoken, typed, and converted to bytes in the back-end.

I'll create a feature request for this there.

**Comment by ShadowJonathan** [comment]
Ah, it appears that multibase already has a user-pronouncable codec: [proquint](https://github.com/multiformats/multibase/blob/master/rfcs/PRO-QUINT.md), which could probably serve this purpose.

**Comment by SgtPooki** [comment]
Closing this issue as it would need to be resolved at lower levels and then supported by kubo before desktop would implement it.
