### ISSUE TITLE
Unable to enable Command Line Tools (snap)

### ISSUE THREAD

**Issue by marathone** [ipfs/ipfs-desktop#1311]
_Please describe what you were doing when this error happened._
Attempting to enable 'IPFS command line tools' in settings.
**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.10.2
- **Electron Version**: 7.1.2
- **Chrome Version**: 78.0.3904.113

**Error**

```
Error: Unable to find pkexec or kdesudo.
    at test (/snap/ipfs-desktop/7/resources/app.asar/node_modules/sudo-prompt/index.js:205:18)
    at /snap/ipfs-desktop/7/resources/app.asar/node_modules/sudo-prompt/index.js:212:47
    at FSReqCallback.oncomplete (fs.js:165:21)
```

**Comment by marathone** [comment]
Forgot to add that this is a snap version, so perhaps I should report it to the snap developer rather than here?

**Comment by hacdias** [comment]
This seems to be an issue because of snap sandboxing restrictions. Thanks @jamescallumyoung for investigating this.

@lidel do you think you could take a look at this?

**Comment by lidel** [comment]
Sadly I don't have bandwidth for debugging this, nor using Snap on my OS. 
But I am happy to review PR if someone wants to contribute a fix!

**Comment by karawitan** [comment]
Please tell how to reproduce the issue

**Comment by lidel** [comment]
For what its worth, the CLI on PATH feature is being deprecated as it caused issues on multiple platforms.
Command line users should follow https://docs.ipfs.io/install/command-line/
