### ISSUE TITLE
Improve UX when updating

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#1488]
Right now user can manually force update via `About` → `Check for Updates`
but they don't get any feedback until its done or fails. Downloading updates may take time on slower connection, producing experience where nothing happens for a long long time.

We could:
- at least do what we do for GC, and set status in menu to `Running (Fetching Update)` (https://github.com/ipfs-shipyard/ipfs-desktop/pull/1420#issuecomment-615884957).
- (optional) additionally, we could pass progress to webui when opened (inspiration: https://github.com/unipept/unipept-desktop/pull/35#issue-384231781)

**Comment by jessicaschilling** [comment]
Both these options are clear and co sister to with how we are already doing things. I’d suggest both.

**Comment by jessicaschilling** [comment]
Menu text changes:
- Gray out "Check for Updates..." and replace text with "Checking for Updates"
- Replace menu status with yellow dot (same as GC) and "Running (Checking for Updates)"

Snackbar feedback text:
- If failed, failure-specific message (what types of failure other than "could not download" do we have?) with link to troubleshoot: at minimum, dist page
- Is there a need for an additional "taking a long time" message or does this just turn into failure on timeout?

**Comment by jessicaschilling** [comment]
Is this something worth addressing in our current batch of small Desktop changes? Not sure if either @lidel or @rafaelramalho19 would have time for it?

**Comment by lidel** [comment]
Closed by https://github.com/ipfs/ipfs-desktop/pull/1758
