### ISSUE TITLE
UX of "Download.." command under the cube menu

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#1499]
> This is mostly a bunch of notes so we don't forget to tackle this UX gap

### Problems

We are missing progress reporting for "Download..." feature under the cube menu.
User is unable to see what is happening, nor to cancel the download if they choose to do so.

AFAIK there is no API for tracking background downloads in go-ipfs, so the download would have to happen in ipfs-desktop process, and progress needs to be passed to WebUI  somehow.

### Unify "Download"  actions

To reduce the amount of code, we could unify behavior of "Download.." command under the cube menu  Desktop with  "Download" action from context menu present in Web UI Files. 

Namely:

- "Download.." command under the cube menu opens WebUI Files and shows download progress, reusing the new UI introduced for imports and downloads.
- When a big directory tree is being downloaded user can close WebUI and download continues as long ipfs-desktop is running. 
- When user opens WebUI again, the ongoing download progress indicator is still there and user can cancel it if they want.

It will require  ipfs-desktop to send "background download" status info to webui somehow. May be tricky if we decide to stop embedding webui in Electron and open it in external browser.

**Comment by jessicaschilling** [comment]
Added to epic https://github.com/ipfs/ipfs-gui/issues/88 since it's part of the whole progress indicator mental model.

**Comment by NatoBoram** [comment]
> AFAIK there is no API for tracking background downloads in go-ipfs

Not *yet*! https://github.com/ipfs/go-ipfs/issues/4028
