### ISSUE TITLE
npm-on-ipfs experiment: Error: spawn npm.cmd ENOENT

### ISSUE THREAD

**Issue by smehmetoglu** [ipfs/ipfs-desktop#1504]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.11.2
- **Electron Version**: 8.2.4
- **Chrome Version**: 80.0.3987.165

**Error**

```
Error: spawn npm.cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by lidel** [comment]
The error suggests you are missing `npm` command.
Make sure you have Node.js and `npm`  (https://nodejs.org/en/) installed on your system and available on `PATH` (available in cmd.exe).
Let us know if that helped.
