### ISSUE TITLE
Improve onboarding via OS-level protocol handler

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#1646]
Right now,  IPFS Desktop installs system-wide protocol handlers (dweb, ipfs, ipns) which converts `ipfs://<cid>` URI to gateway URL and opens that in default browser.

It is fine, but  may be confusing on the first use.

We could improve this behavior and show a dialog window, where user can choose how to open IPFS resource via radio-button-like selector:

- open from public gateway in the default web browser (default)
- open from a local gateway (show only if daemon in running)
- open in webui/Files (show only if daemon in running)
- open in webui/Explore (show only if daemon in running)
- (checkbox) remember the choice for the future
  - should be accompanied by a toggle in menubar menu: _"Ask how to handle IPFS URIs"_ so user can change their mind later

(thx @aschmahmann for noticing that onboarding is especially confusing if user's default browser is not the one with ipfs-companion)

**Comment by jessicaschilling** [comment]
This is also a good opportunity to emphasize on first use that Desktop is acting as the intermediary - otherwise, the flow is like this:
- user types `ipfs://QmY7Yh4UquoXHLPFo2XbhXkhBvFoPwmQUSa92pxnxjQuPU` into their browser bar
- they get a "do you want to open this in IPFS Desktop?" dialog, and click "OK"
- but then they just stay in their browser and see their requested resource in a new tab
This is super-confusing if you've never encountered it before.

**Comment by jessicaschilling** [comment]
Quick mockup of menu item mentioned above:

![image](https://user-images.githubusercontent.com/1507828/93375818-f19fba00-f815-11ea-92d2-c1d37cb8b56c.png)

**Comment by jessicaschilling** [comment]
Quick mockup of choice modal (note this could appear over whatever screen the user currently has open in Desktop):
![image](https://user-images.githubusercontent.com/1507828/93378732-1f86fd80-f81a-11ea-8066-3128916223b7.png)

**Comment by lidel** [comment]
Thank you, yes, this would do the trick.

nit: this modal is specific to Desktop app, so I think it should not be part of WebUI, but a separate window that loads the modal page.

**Comment by jessicaschilling** [comment]
> a separate window that loads the modal page
You mean a browser tab just with this dialog on it? Confused.

**Comment by lidel** [comment]
This is a significant UX improvement, bumped a priority a bit.

ps. I suspect protocol handler does not work everywhere (eg. https://github.com/ipfs-shipyard/ipfs-desktop/issues/1549).

**Comment by unmellow** [comment]
Not sure if this is the best place to mention this but I think it would be a good idea for you to a url in the style of [lokinet](https://github.com/oxen-io/lokinet) 
E.G. http://awsomeipfs.io.ipns vs the current system 
As lokinet recognize all domains as their own origins 


Not actually knowledgeable of the low level of how this works but untill the web 2.0 APIs are complete you should in theory be able to imatate whatever it is that they've done

**Comment by hacdias** [comment]
I'm now working on this on #1966. I also want to add that the Explore page does NOT support IPNS links. Options I see:

1. Ask this prompt for each different scheme: ipfs://, ipns://, dweb:/ipfs, dweb:/ipns
2. Default to opening on files or browser for IPNS.

2 is easier to implement than 1.

What do you think?

**Comment by lidel** [comment]
The proliferation of `ipns://` and `ipfs://` addresses for website hosting changed the feasibility here.

URIs are now natively supported by Brave and ipfs-chromium, and IPFS Desktop trying to capture them and opening them in IPLD Explorer or  Files explorer becomes effectively harmful, as miss-click will break websites for less technical users, especially if the checkbox to remember choice is checked.

Due to this, I'm closing this, as it is no longer something desired in user-friendly tool.
