### ISSUE TITLE
HaikuOS when?

### ISSUE THREAD

**Issue by ojej** [ipfs/ipfs-desktop#1781]
When Haiku os version?

**Comment by sp00ck** [comment]
Good idea.

**Comment by lidel** [comment]
I would say PRs welcome, but given that Haiku does not support Electron (https://github.com/electron/electron/issues/13762) I'm closing this as unlikely (feel free to reopen if you make Electron + [electron-builder](https://github.com/electron-userland/electron-builder) work on HaikuOS).

That being said, I'd like to propose an alternative:  https://github.com/ipfs-shipyard/go-ipfs-desktop#readme which is IPFS Desktop without Electron. It uses sme go libraries for UI, but feels like smaller number of things to fix, if someone wants to make it work. 

Pinging @kallisti5  for sanity check, as I am not familiar with golang support on HaikuOS :)

**Comment by kallisti5** [comment]
We have NodeJS, but no electron or electron-builder support.
We have a golang port, but it's pretty incomplete and unstable.

We have a pretty solid Rust port, but that doesn't help much here ^_^

So the answer is, "go-ipfs is a possibility if our go port improves".  Given how golang works (and that Haiku is pretty standard posix), go-ipfs shouldn't need any changes to function on Haiku once our go-lang port improves.
