### ISSUE TITLE
RPM for OpenSUSE Linux

### ISSUE THREAD

**Issue by 0kalekale** [ipfs/ipfs-desktop#1794]
- OS: OpenSUSE tumbleweed
 - Version of IPFS Desktop UI v2.11.4 Revision 69cd414

**Describe the bug**
The rpm package provided will not install on opensuse because of how the dependecy is named
libuuid on opensuse is libuuid1 
nss on opensuse is mozilla-nss

**To Reproduce**
1. ```rpm -i {packagename}.rpm```
2. ``` error: Failed dependencies:
        libuuid is needed by ipfs-desktop-0.14.0-1.x86_64
        nss is needed by ipfs-desktop-0.14.0-1.x86_64 
    ```

**Expected behavior**
ipfs desktop should be installed as expected as libuuid1 and mozilla-nss is installed, but due to dependecy naming it wont install,


**Additional context**
I managed to get it working by ```rpmrebuild -enp ipfs-desktop-0.14.0-linux-x86_64.rpm``` and renaming the dependency. 

suggestion: provide a seperate rpm package for opensuse with the modified  dependency names.

pic related is how the pacakge should look for opensuse linux. 
![rpm](https://user-images.githubusercontent.com/31927746/113329165-f99bf300-933c-11eb-8937-35833b804c53.png)

**Comment by 0kalekale** [comment]
also here is the rpm package i build after modifying the dependency names 

https://ipfs.io/ipfs/QmZgyDf2iyrTfcs2LWeJi8Z9Mz35GHgkPNZraAWzxMy63A

**Comment by lidel** [comment]
@0kalekale is the issue still present in [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0)?

We have limited bandwidth and are unable to QA and produce packages for every distribution. 
If you are a user, `AppImage` should work for you on most distros. 

If you want to maintain a package for your distro, we provide `.tar.xz` variant that can be used in your build pipeline.
We could add it next to AUR at https://github.com/ipfs/ipfs-desktop#install
