### ISSUE TITLE
bug on load file 

### ISSUE THREAD

**Issue by icreator** [ipfs/ipfs-desktop#1797]
I browse file:  
QmRkp4PuZTr7sY6Fc7UVC89A6d7JCXri14VjjB824ZF6Av

then see Info and click Load - then screen set:  

![image](https://user-images.githubusercontent.com/5246904/113471568-eafd2b00-9465-11eb-8afe-b37ae402828a.png)

then it frozen ((

I use windows .exe

**Comment by lidel** [comment]
@icreator please reopen if this is still happening in [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0) and describe what exact steps lead to this (just entering CID in the top input and clicking on "Browse" ?)
