### ISSUE TITLE
After selecting to share a pin, there is no way to go back

### ISSUE THREAD

**Issue by bobinson** [ipfs/ipfs-desktop#1799]
- OS: [ Windows 10]
 - Version of IPFS Desktop [ 0.14.0]

**Describe the bug**
After selecting share pins, there is no way to go back

**To Reproduce**
1. Go to Pins
2. Click on one of the pins - in this case a simple file
3 Click on the right side button to select more options
4. Select the Share Pin option
5. A screen with no options to go back or escape is presented. Even closing the app results in the same.
6. Quitting the app from tray icon and restarting helps to regain the normal application

**Expected behavior**
A means to share the file or folder should be provided and the user should be allowed to go back to other areas of the application.

**Screenshots**

![image](https://user-images.githubusercontent.com/18070249/114024055-3ca41c00-9891-11eb-85be-0008f3ce7407.png)

![image](https://user-images.githubusercontent.com/18070249/114022625-99063c00-988f-11eb-89ab-7e66063d103b.png)

- Logs : couldn't find any.

**Comment by lidel** [comment]
Pins screen was removed in [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0) – see https://github.com/ipfs/ipfs-webui/issues/1773#issuecomment-828886731 for rationale why + a way to do one-time import to MFS, if you need them for some reason.
