### ISSUE TITLE
lnstaller integrity check has failed.Common causes includeincomplete download and damaged media. Contact theinstaller's author to obtain a new copy. 完整性检查失败。常见原因包括下载不完整和媒体损坏。联系安装程序的作者获得一个新的副本。

### ISSUE THREAD

**Issue by Mr-Tieguigui** [ipfs/ipfs-desktop#1800]
- OS: [e.g. macOS, Windows, Linux]
 - Version of IPFS Desktop [e.g. 0.11.1]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lidel** [comment]
Please retry with https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0 (see note at the bottom)
