### ISSUE TITLE
Trying to download a file leads to stuck interface

### ISSUE THREAD

**Issue by artiface** [ipfs/ipfs-desktop#1801]
I'm new to IPFS, just trying to understand how it works, so its very possible I did something incorrectly.  

I was trying to download the quick-start file in the pins that were installed with the application.   After I selected download the application goes to just a white screen, and there is no way out.  Even after restarting the application it is now just a white screen.

![2021-04-09 14_35_17-_ipfs_QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc _ IPFS](https://user-images.githubusercontent.com/6565866/114226670-dcb97e00-9941-11eb-833b-64403d1b7c84.png)

Why cant I download files?  How do I correct the ipfs-desktop application so I can use it again?

**Comment by artemmolotov** [comment]
Same problem.

**Comment by lidel** [comment]
Can you provide steps how to reproduce this?
Is this end result of some menu operation? 
Are you both running Windows?

**Comment by artemmolotov** [comment]
> Can you provide steps how to reproduce this?

In my case, there was something similar to this:
1. Enter hash of the 5GB file into search input
2. Click `Browse`
3. Click `...`
4. Click `Pin`
5. Click `...` again
6. Click `Download`
7. Click `Status` in the main menu
7. Wait some time with or without jumping to another page

> Is this end result of some menu operation?

It can occur when you changing the page or lossing and the gaining focus on the IPFS window. A user can fix the problem by clicking "Restart" in the tray icon menu.

> Are you both running Windows?

Windows 10 1909 x64, IPFS UI v2.11.4
