### ISSUE TITLE
The MacOS security blocker is back

### ISSUE THREAD

**Issue by king612** [ipfs/ipfs-desktop#1802]
- OS: Mac
 - Version of IPFS Desktop [e.g. 0.11.1] latest from your website

**Describe the bug**
After following your instructions carefully, running 'ipfs' from the command line, even with sudo, I get the dreaded 'can't run this app because it cannot be verified'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lidel** [comment]
Hm.. IPFS Desktop is signed and notarized, so this is a problem with go-ipfs itself.

Please see https://github.com/ipfs/go-ipfs/issues/6756, if that does not help, fill new issue in https://github.com/ipfs/go-ipfs/issues/new/choose
