### ISSUE TITLE
ipfs cli command missing

### ISSUE THREAD

**Issue by MysticRyuujin** [ipfs/ipfs-desktop#1805]
- OS: Linux Mint 10
 - Version of IPFS Desktop: 0.14.0

**Describe the bug**
Disclaimer, first time trying to use any ipfs tools.

First I tried using the AppImage. After running the app I thought I would try to check out the cli, but `ipfs` command was not found. So, I tried to install the `ipfs` tool. First, I tried to install it via snap (yes I have snaps enabled on Linux Mint) but that resulted in it wanting to init a new repo. So I figured ok, I'll try to install ipfs-desktop through snap too. That...didn't work either. When I started ipfs-dekstop through snap it initialized its own repo....

Then I did more research and I found a few closed issues here about the `ipfs` cli tool being installed / placed in the PATH when installing, and they seemed to suggest that if I installed via `deb` package that I would get a working ipfs-desktop, and ipfs cli from that single install...That didn't seem to work either?

So here I am, trying to figure out how to get a working ipfs-desktop install AND a cli `ipfs` working together nicely.

**To Reproduce**
See above description :smile: 

**Expected behavior**
I install ipfs-desktop, I get `ipfs` cli tool..OR there are some clear instructions to make the two things work together...

**Screenshots**
N/A

**Additional context**
https://github.com/ipfs/ipfs-desktop/issues/727
https://github.com/ipfs/ipfs-desktop/issues/1039

**Comment by MysticRyuujin** [comment]
I don't know in what order of operations I did to get this fixed, but I think that installing ipfs-desktop from the `deb` put the repo into `~/.ipfs` and now manually installing the go-ipfs binary into `/usr/local/bin` has it working...but I don't know why installing the `deb` didn't include the `ipfs` binary...

**Comment by lidel** [comment]
We had experiment in the past when ipfs-desktop added `ipfs` to `PATH`,  but it was too expensive to maintain: it did not work reliably, clashed with `ipfs` installed by some other package, and we ended up deprecating it (it is removed from UI right now).

In short, if you want `ipfs` in terminal, follow https://docs.ipfs.io/install/command-line/ or use go-ipfs daemon package for your OS.  
`ipfs` will inspect `$IPFS_PATH/api` file and connect to it by default, so just make sure `IPFS_PATH` points at the same repo as one used by ipfs-desktop. You can also override the API addres via `ipfs --api` if you choose to have multiple repos.
