### ISSUE TITLE
Blank window when download, Fedora

### ISSUE THREAD

**Issue by AbsenceGameDev** [ipfs/ipfs-desktop#1809]
- OS: Fedora 34 (beta)
 - Version of IPFS Desktop: 0.14.0
 - Version of Agent:             go-ipfs v0.8.0
 - Version of UI:	            2.11.4

**Describe the bug**
Blank window bug.

**To Reproduce**
1. Installed the rpm locally, running the desktop client.
2. Browse to any CID
3. Pick files and select download
4. See error (Blank window, no UI), the commandline prints "info: [web ui] window hidden"

**Expected behavior**
A download to start

error.log file was 0 bytes in size.
[combined.log](https://github.com/ipfs/ipfs-desktop/files/6377565/combined.log)

**Comment by lidel** [comment]
@AbsenceGameDev I assume this is fixed in [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0) which includes refactored webui. 
Feel free to reopen if its still happening with v0.15.0.
