### ISSUE TITLE
?

### ISSUE THREAD

**Issue by vladdelonge** [ipfs/ipfs-desktop#1810]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.14.0
- **Electron Version**: 11.2.3
- **Chrome Version**: 87.0.4280.141

**Error**

```
Error: No application in the Launch Services database matches the input criteria.
```

**Comment by olizilla** [comment]
@vladdelonge can you give any more details? how did you install IPFS Desktop? How are you trying to start it?

**Comment by lidel** [comment]
@vladdelonge please retry with [v0.15.0](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.15.0) and reopen with more details, if still present.
