### ISSUE TITLE
How to get the path where ipfs-desktop have installed go-ipfs?

### ISSUE THREAD

**Issue by DaniellMesquita** [ipfs/ipfs-desktop#1819]

**Comment by UnKnoWn-Consortium** [comment]
First, as the welcome bot suggested, it would be easier to get help at https://discuss.ipfs.io. Second, it would be great if you can include your OS and app version. 

All in all, IPFS Desktop uses its bundled IPFS runtime. If the OS you use is Windows 10 and IPFS Desktop is installed with the default path, you can find the bundled ```ipfs.exe``` at ```C:\Program Files\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs```.

**Comment by lidel** [comment]
Next time ask support questions like this on https://discuss.ipfs.io where more eyes are looking :pray: 
If you are using Windows, you may find https://github.com/ipfs/ipfs-desktop/issues/1656 informative.
