### ISSUE TITLE
Tray icon / Download / Cancel doesn't work

### ISSUE THREAD

**Issue by andrasfuchs** [ipfs/ipfs-desktop#1830]
- OS: Windows 10
 - Version of IPFS Desktop: 0.15.0

**Describe the bug**
The "cancel" button doesn't close the download dialog in the tray icon menu.

**To Reproduce**
1. Start IPFS Desktop
2. Right click on its tray icon
3. Select "Download..."
4. A dialog opens up with Next and Cancel buttons
5. Click on the Cancel button
6. Nothing happens

**Expected behavior**
I would expect the modal dialog to close.
Also, if I click on the "Download..." menu item multiple times without closing the previous model dialogs, multiple dialogs will be shown. I would expect to return the focus to the already opened dialog if there is one, without creating a new dialog.

**Screenshots**
Tray icon and download menu:
![image](https://user-images.githubusercontent.com/910321/120915770-f0653480-c6a5-11eb-8a8f-4f30912dafaf.png)

Download dialog:
![image](https://user-images.githubusercontent.com/910321/120915804-1be81f00-c6a6-11eb-9295-b11f29068497.png)

**Comment by lidel** [comment]
I believe this was fixed in v0.15.1 – please update https://github.com/ipfs-shipyard/ipfs-desktop/releases/latest
