### ISSUE TITLE
Cannot Run IPFS v 0.15 on Mac - Permissions issue

### ISSUE THREAD

**Issue by anthraxblast** [ipfs/ipfs-desktop#1834]
- OS: [e.g. macOS, Windows, Linux]
 - Version of IPFS Desktop 0.15.0 on Mac (Big Sur [11.4)](![ipfs_error](https://user-images.githubusercontent.com/84252396/121109285-1a127e80-c7c0-11eb-99d6-3808ce353c4d.png))
 
**Describe the bug**
When I try to install IPFS Desktop on my MacBook Air, I get this error message:
You do not have permission to open the application “IPFS Desktop”.
Contact your computer or network administrator for assistance.
Note that I went to the "Security and Privacy" control panel on my Mac it it allows apps downloaded from App Store and identified developers.  I've downloaded a bunch of recent 3rd party apps and they all worked fine.

This is a personal notebook where I'm the admin account (I triple checked).

**To Reproduce**
1. Download  IPFS Desktop for Mac 0.15.
2. Unzip.
3. Open.

**Expected behavior**
The application should open.

**Screenshots**
If applicable, add screenshots to help explain your problem.  See attached.

**Additional context**
I got an older version of IPFS to work fine on this computer - not sure why Mac is blocking it now - it could be the new O/S.

**Comment by lidel** [comment]
@olizilla mind triaging this one and checking if you can reproduce?

**Comment by lidel** [comment]
Sounds like you used `.zip` for some reason, please use `.dmg` which is signed and should not produce security errors.
The latest one is at https://github.com/ipfs/ipfs-desktop/releases/download/v0.15.1/IPFS-Desktop-0.15.1.dmg

**Comment by AlexxNica** [comment]
@lidel, is this issue really solved, though? Since we offer `.zip` along with `.dmg` and others for download with each release, I think we can make an effort to triage and solve this. What do you think?
