### ISSUE TITLE
Should "choco install ipfs-desktop" be called with admin rights?

### ISSUE THREAD

**Issue by ruifortes** [ipfs/ipfs-desktop#1848]
The title and the old Clash song says it all... 

``` sh
PS C:\Users\me> choco install ipfs-desktop
Chocolatey v0.10.15
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.


 Do you want to continue?([Y]es/[N]o):
```

Should I "Yes" or should I "No"??? :-P

**Comment by lidel** [comment]
IPFS Desktop does not require admin, if you use standalone .exe installer you can install it in single user.
If you experience any issues without admin, its most likely specific to choco, and you can find support resources at https://chocolatey.org/support

**Comment by ruifortes** [comment]
Hi. No issues just extreme fear subtle bugs from incorrect installation :-P
By the way, ipfs-desktop making "system interrupts" CPU usage run amok seams to have disappeared since I reinstalled the OS :-)
