### ISSUE TITLE
Enable Wiki

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1854]
I like to start with a list in a wiki which tracks which (home) routers have issues with which version of IPFS and if there's a workaround available or a specific setting.

This requires a wiki tab here. 

Alternatively, we could create a page in the docs for this? But they are so bound to certain versions etc. I think a wiki would be easier.

Let me know which works best for you.

Reference: https://github.com/ipfs/go-ipfs/issues/3320#issuecomment-865820006

**Comment by lidel** [comment]
Good idea! This is not specific to desktop app, and  adding it to https://docs.ipfs.io/how-to/  will make the list easier to discover.

Ref. 
-  you can add new page by submitting a PR against https://github.com/ipfs/ipfs-docs/tree/main/docs/how-to
- formatting tips: https://v1.vuepress.vuejs.org/guide/markdown.html
