### ISSUE TITLE
Adding a file with right click in explorer adds it to the MFS and pins it

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1857]
- OS: Windows
 - Version of IPFS Desktop 0.16.0

**Describe the bug**
Adding files via right click in the explorer is pretty cool, but instead of adding the file just to the MFS, it is also locally pinned. Why?

I mean, the only reason to pin an item in the MFS is when it's lazily added via CID and you want it to be downloaded completly.

**To Reproduce**
1. Add a file via right-click in explorer -> Add to ipfs
2. Open the IPFS GUI

**Screenshots**
![ipfs_desktop_screenshot_bugreport_imported_files_pinned](https://user-images.githubusercontent.com/614929/123209304-b3c87400-d4c0-11eb-87a5-61dd49c66ae1.png)

**Comment by lidel** [comment]
This is a bug, we should not pin it, adding to MFS is enough.
