### ISSUE TITLE
Click on notification after import of files leads to an empty page

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1858]
- OS: Windows
 - Version of IPFS Desktop 0.16.0

**Describe the bug**
When a file is imported via right click in the explorer, a notification pops up to show the completion. The notification can be clicked by the user, which opens IPFS-Desktop on an empty page.

This doesn't really look very helpful.

**To Reproduce**
1. Click right on a file in the explorer -> Import to IPFS
2. Wait for the notification
3. Click on the notification

**Expected behavior**
Not sure... show the files?

**Screenshots**
![ipfs_desktop_screenshot_bugreport_imported_files_click_on_notification](https://user-images.githubusercontent.com/614929/123209834-79aba200-d4c1-11eb-8e59-758042e78dfa.png)

**Comment by lidel** [comment]
Thanks! Already tracked in https://github.com/ipfs/ipfs-desktop/issues/1815
