### ISSUE TITLE
make dhtclient the default again

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1871]
@lidel so I propose we change that back to `dhtclient` as long as we cannot ask the user if this is a mainly mobile computer since we would burn too much battery life.

_Originally posted by @RubenKelevra in https://github.com/ipfs/ipfs-desktop/issues/1859#issuecomment-877710249_

**Comment by RubenKelevra** [comment]
I mean isn't https://github.com/ipfs/ipfs-desktop/blob/c345eccc91a8612c182cb519c20b0895a07c17aa/src/common/store.js#L11 overwriting the config anyway?

**Comment by lidel** [comment]
Corect, nothing to do here, `dhtclient` is the default.

What we discussed in https://github.com/ipfs/ipfs-desktop/issues/1859#issuecomment-892054779 is adding UI for switching from `dhtclient` (default) to `dht` (server if publicly diallable)
