### ISSUE TITLE
Constant High CPU Usage on Windows

### ISSUE THREAD

**Issue by mohammedpatla** [ipfs/ipfs-desktop#1872]
- OS: Windows
 - Version of IPFS Desktop 0.16.1
 - System Specs: Ryzen 5900x (12core,24 thread processor), 32 GB RAM, Windows 10 latest build.

**Describe the bug**
Consistent high usage of CPU. It can go up to 80% at times, which is a lot of usages. I have only about 50GB of data pinned but not a lot of uploads or download going on either to commission this much usage.

The CPU usage drops some times in a cycle but picks up again and stays high for longer times than needed. Avg usage is about 35% of my CPU power that's 4 Cores running at full power for some reason.

**To Reproduce**
1. Install the latest version of the software.
2. Have some big pined data objects.
3. Leave it running in the background and monitor it through the task manager. 

**Expected behavior**
At most, it should spike the CPU during a lot of usages, but keeping high CPU usage is very weird, as the Network and disk usage are also not followed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16710191/125641743-31078fba-5e1d-4bd2-b5cc-b0a157d8b2a3.png)

**Additional context**

[error.log](https://github.com/ipfs/ipfs-desktop/files/6816916/error.log)
[combined.log](https://github.com/ipfs/ipfs-desktop/files/6816917/combined.log)

**Comment by SerafDosSantos** [comment]
I second this problem. I paused my instances until the problem is solved. My oldest CPU goes nuts once in a while with version 0.16.1, my newest one also goes high once in a while, but the fans doesn't scream for cooling with the latter.

**Comment by unbeatable-101** [comment]
Does this seem like your issue? https://github.com/ipfs/go-ipfs/issues/8256

**Comment by mohammedpatla** [comment]
@unbeatable-101 Looks like it, although I can't confirm if the solution https://github.com/lucas-clemente/quic-go/pull/3231 fixes it.

**Comment by unbeatable-101** [comment]
Try building go-ipfs from source, then tell ipfs desktop to use a custom binary

**Comment by unbeatable-101** [comment]
[ipfs.zip](https://github.com/ipfs/ipfs-desktop/files/6844657/ipfs.zip)

I tried cross-compiling if you can't build yourself

**Comment by mohammedpatla** [comment]
@unbeatable-101 Nope that file does not work and I have not had much success in compiling from source.

**Comment by unbeatable-101** [comment]
What issues are you having?

**Comment by mohammedpatla** [comment]
@unbeatable-101 On further testing your IPF binary does work, I was just not running the daemon lol.

Just after launching it seems to work well, with no excess CPU usage or memory. Stays about 130 MB RAM usage and around 1% CPU usage with my build. Will let this run overnight and see how its in the morning.

**Comment by mohammedpatla** [comment]
I confirmed I don't use more than 300 MB in RAM. And CPU usage is between 0.1%-1.5%

![image](https://user-images.githubusercontent.com/16710191/126349078-ac43f988-4c9f-4c71-8017-8477965e859b.png)

Looks like this new binary has to be merged in, or wait until 0.91

**Comment by SerafDosSantos** [comment]
[ipfs/go-ipfs#8256](https://github.com/ipfs/go-ipfs/issues/8256) fixed it for me, thanks @unbeatable-101 !

**Comment by unbeatable-101** [comment]
The fix will be officially released in 0.9.1
