### ISSUE TITLE
ipfs-desktop becomes blank when trying to download a file

### ISSUE THREAD

**Issue by fretzo** [ipfs/ipfs-desktop#1874]
- OS: Linux
 - Version of IPFS Desktop: 0.14.0-2 [AUR]
 - UI version: v2.11.4 [AUR]
 - go-ipfs: v0.8.0 [Arch]

**Describe the bug**
When i try to download a file from ipfs-desktop, the app becomes all blank, and the file is not downloaded.

EDIT: if downloading a file that is on the same computer, there is no issue, but when downloading a file that is on another node, the app goes blank.

Downloading files works through the cli.

**To Reproduce**
1. Try to Download a file

**Expected behavior**
File is downloaded, app doesn't go blank.

[combined.log](https://github.com/ipfs/ipfs-desktop/files/6855489/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/6855490/error.log)

**Comment by lidel** [comment]
I suspect this was due to https://github.com/ipfs/ipfs-webui/issues/1819  → this should be fixed in ipfs-desktop v0.16.3 which shipped fix for linked issue. 
Please update: https://github.com/ipfs/ipfs-desktop/releases/latest
