### ISSUE TITLE
IPFS Desktop just shows a blank screen

### ISSUE THREAD

**Issue by unbeatable-101** [ipfs/ipfs-desktop#1875]
- OS: macOS
 - Version of IPFS Desktop 0.16.1

**Describe the bug**
IPFS Desktop.app just shows a blank screen upon opening

**To Reproduce**
1. Open the app

**Expected behavior**
It shows the webui

**Screenshots**
<img width="1106" alt="Screen Shot 2021-07-22 at 00 29 21" src="https://user-images.githubusercontent.com/58151048/126590041-caf90545-4227-4d66-956f-c7991b62937f.png">
<img width="1106" alt="Screen Shot 2021-07-22 at 00 27 27" src="https://user-images.githubusercontent.com/58151048/126590043-d91ec4d1-ee88-48f1-923e-9c325c0187da.png">
<img width="1106" alt="Screen Shot 2021-07-22 at 00 27 19" src="https://user-images.githubusercontent.com/58151048/126590046-0cf6e99f-c242-45aa-b455-5cb0def32cf5.png">

**Additional context**

[combined.log](https://github.com/ipfs/ipfs-desktop/files/6859978/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/6859979/error.log)

**Comment by lidel** [comment]
Seems that you are using external  `ipfs` binary  that is not bundled with ipfs-desktop, and it does not support `daemon` mode?

```
 Command failed with exit code 1: /opt/homebrew/bin/ipfs daemon --migrate --routing dhtclient --enable-pubsub-experiment --enable-namesys-pubsub --enable-gc
ERROR: unknown command "daemon" 
```

Did you set up use of `/opt/homebrew/bin/ipfs` by manually editing the config, or was it picked up because was on `PATH` ?

**Comment by unbeatable-101** [comment]
The issue isn't happening any more, but what I did is since `/opt/homebrew/bin/ipfs` is actually an alias and not a binary, I put the ipfs binary there, set that as the custom binary from the toolbar options, and then put the alias back which points to the binary.
