### ISSUE TITLE
FreeBSD Package is ... Linux?

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/ipfs-desktop#1877]
- OS: FreeBSD
 - Version of IPFS Desktop: 0.16.1

**Describe the bug**
FreeBSD package is labelled as "linux", and install yields `pkg: wrong architecture: Linux:5:x86:64 instead of FreeBSD:13:amd64`. I noticed the package name also includes "linux" in it.

**To Reproduce**
1. Download the "FreeBSD" package [here](https://github.com/ipfs/ipfs-desktop#linuxfreebsd)
2. `pkg add ./ipfs-desktop-0.16.1-linux-x64.freebsd`

**Expected behavior**
Package installs.

**Additional context**
Discovered in [this thread](https://discuss.ipfs.io/t/how-can-i-run-freebsd-version/11818?u=discordian).

I extracted the archive, and it really does look like a Linux binary, not a FreeBSD binary:

```
$ file ipfs-desktop 
ipfs-desktop: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=8e2a5573ce751fd59276672df63d46e4158cac08, not stripped
```

**Comment by lidel** [comment]
I believe this is a binary optimized for Linux interop layer provided by FreeBSD:
https://docs.freebsd.org/en/books/handbook/linuxemu/

Note that linux binary support needs to be enabled first: 
> By default, Linux® libraries are not installed and Linux® binary compatibility is not enabled. Linux® libraries can either be installed manually or from the FreeBSD Ports Collection.

I opened https://github.com/ipfs/ipfs-desktop/pull/1878 to clarify this requirement.
Lmk if this solves the issue.

**Comment by TheDiscordian** [comment]
Yeah looks good to me! Much clearer
