### ISSUE TITLE
npm complains about an old lockfile

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1881]
- OS: Linux
 - Version of IPFS Desktop: 0.16.2

**Describe the bug**
npm complains about an old lockfile:

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
```

**Comment by lidel** [comment]
@RubenKelevra what are your node  and npm versions?

Please post output of `node --version` and `npm --version`

**Comment by RubenKelevra** [comment]
```
$ node --version
v16.6.1
```

```
$ npm --version
7.20.4
```

**Comment by lidel** [comment]
Thanks.
My understanding is that there is nothing to do here – we run build with LTS, which is 14.x at the moment – https://nodejs.org.
Mentioned warning can be ignored.
