### ISSUE TITLE
outdated uuid module which "is known to be problematic"

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1882]
- OS: Linux
 - Version of IPFS Desktop: 0.16.2

**Describe the bug**
npm complains about a problematic outdated version of uuid:

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by lidel** [comment]
afaik we dont use UUIDs for anything important, but PR welcome

**Comment by RubenKelevra** [comment]
This is a dependency of request, so maybe it's incompatible with newer versions?

@mikeal will the dependencies be updated?
