### ISSUE TITLE
Avoid running Renderer when WebUI is not shown

### ISSUE THREAD

**Issue by unbeatable-101** [ipfs/ipfs-desktop#1893]
**Is your feature request related to a problem? Please describe.**
Using electron takes up a lot of memory compared to other native programs.

**Describe the solution you'd like**
Write a native app that is only the menubar (e.g. Status, Files, and Peers would open your web browser).

**Describe alternatives you've considered**
Don't start IPFS Desktop Helper (Renderer) if `openWebUIAtLaunch` is set to `false`, rewrite the whole app to be native (Maybe use the bundled WKWebView?)

**Comment by lidel** [comment]
@mvdan  created  a light rewrite without Electron at: https://github.com/ipfs-shipyard/go-ipfs-desktop
You can give it a spin and report issues/feature requests in that repo – it is unofficial (unsigned) for now, but we want to provide it as alternative to Electron at some point.

**Comment by unbeatable-101** [comment]
> ps. created a light rewrite without Electron at: ipfs-shipyard/go-ipfs-desktop – give it a try and report issues/feature requests in that repo – it is unofficial (unsigned) for now, but we want to provide it as alternative to Electron at some point.

Oh nice, this is basically exactally what I wanted

**Comment by cyberpunkrocker-zero** [comment]
+1 for Electron-less go-ipfs-desktop! I wanted to use ipfs-desktop on my ageing laptop, but it was using so much resources that it was impossible to keep it running it when the laptop was off AC. Go-ipfs-desktop is a perfect low-power option.

**Comment by tinytb** [comment]
backlog grooming: we are considering and experimenting with alternatives to electron, e.g. [here is a basic attempt to use wails](https://github.com/SgtPooki/ipfs-desktop-wails) instead of electron. Closing this issue, as these efforts will be tracked elsewhere:
- https://github.com/ipfs/ipfs-desktop/issues/2184
- https://github.com/ipfs/ipfs-desktop/issues/867
