### ISSUE TITLE
Unblock Electron Update

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#1902]
We are 2 versions behind, waiting for https://github.com/electron-userland/spectron/releases to ship something compatible with the latest Electron.

**Comment by hacdias** [comment]
I will analyse this.

**Comment by lidel** [comment]
Even tho Electron 15 shipped, we can't update.
This is still blocked by the lack of [Spectron](https://www.electronjs.org/spectron) (tool we use for E2E tests) compatible with Electron 14.

**Comment by lidel** [comment]
so.. spectron is dead: https://github.com/electron-userland/spectron/issues/1045 :skull: 

means we need to invest more work here, and rewrite e2e tests to use playwright:
- https://github.com/electron-userland/spectron/issues/896#issuecomment-860134329
- https://github.com/tanshuai/electron-playwright-e2e-test-quick-start

**Comment by hacdias** [comment]
I will look into moving to playwright.
