### ISSUE TITLE
Impossible / very hard time to connect jsipfs node to the UI

### ISSUE THREAD

**Issue by LucSalommez** [ipfs/ipfs-desktop#1907]
- OS: MacOS
 - Version of IPFS Desktop  v2.13.0

**Describe the bug**
Hello, I am trying to develop a NodeJS API which enables users to interact with an IPFS node owned by the API.

What I want to do is for testing purposes to verify that when I programmatically pin a new file, this one is currently retrieved and pinned on the node I create in my NodeJS code.

I also expect that shutting down and restarting the NodeJS code won't have an impact on data persistence as it will always look at the same folder (`~/.jsipfs`).

I have a very hard time to use the IPFS Desktop as a dashboard to see the current state of my jsipfs node running with my API.

I tried following the instructions from the UI that is displayed when no connection can be established but without success.
I also tried to connect using `/ip4/127.0.0.1/tcp/4002` instead of `5001` as proposed, because my code displays the `4003` and `4002` ports as the one being used.

I tried changing the `config` file of ipfs-desktop in order to point to my `.jsipfs` folder instead of `.ipfs`.
I can't even use the cli command `jsipfs repo stat` as an alternative to ipfs-desktop as the folder is already locked by my API.

I am sorry to use a Bug report for my issue but I think :
- I might not be the only one struggling so a bit of posterity can be useful
- I didn't find any Discord server or related for support for that kind of questions.

**To Reproduce**
1. Start a daemon from JS with for example :
```
import * as IPFS from "ipfs-core"
const node = await IPFS.create()
```
2. If you try any command with the jsipfs cli like `jsipfs repo stat` you will be refused access, which confirms the node runs well.
3. Edit the config file of ipfs-desktop to make it point to the jsipfs repo. Especially change these two lines :
```
	"ipfsConfig": {
		"type": "js",
		"path": "/Users/nex/.jsipfs",
                ...
	},
        ....
```
4. Start ipfs-desktop
5. It should not be able to connect to the node

**Expected behavior**
I expect the UI to be a reflection of the repo that is hosted in the `.jsipfs` folder. When a file is added from JS for example, it should be seen on the IPFS Desktop UI.

**Additional context**
My issue seem very common but I couldn't find anything related when searching on internet.
I am sorry if the solution is trivial.

Thank you for your help.

[combined.log](https://github.com/ipfs/ipfs-desktop/files/7150136/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/7150137/error.log)

**Comment by LilLoveBug** [comment]
whoever wrote u this is hacking my acct

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LucSalommez** [comment]
I have discovered https://discuss.ipfs.io/ which is more suitable for my issue.
I ended up finding an other way to connect the UI to my daemon.

You can follow the discussion here : https://discuss.ipfs.io/t/impossible-very-hard-time-to-connect-jsipfs-node-to-ipfs-desktop/12184/2

I am closing this issue.
