### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by thomaslgregoryjr** [ipfs/ipfs-desktop#1921]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.17.0
- **Electron Version**: 13.5.1
- **Chrome Version**: 91.0.4472.164

**Error**

```
Error: EBUSY: resource busy or locked, copyfile 'C:\Users\thoma\.ipfs\repo.lock' -> 'F:\IPFS\.ipfs\repo.lock'
```

**Comment by SgtPooki** [comment]
@thomaslgregoryjr can you describe what you were doing when you received this error? 

Sometimes, lock file errors like these pop up when attempting to start the ipfs-desktop app when a daemon is already running. Is there another daemon running already?
