### ISSUE TITLE
Can IPFS-Desktop be configured to monitor private network?

### ISSUE THREAD

**Issue by lonnietc** [ipfs/ipfs-desktop#1925]
Hello,

A bit new to IPFS and the IPFS-Desktop.

I am working on setting up a private network to test some things and am wondering if the IPFS-Desktop can be configured to monitor the IPFS Private nodes when they are online?

Any help would be greatly appreciated.

**Comment by SvenDowideit** [comment]
#2223 - says: "as discussed in yesterday's triage meeting. IPFS Desktop is built with public networks in mind."

I too would love to use the full power of IPFS, which will only work if I can have both a private and public data store.

**Comment by SgtPooki** [comment]
I was marking this one with a label so i could grab it later yea

**Comment by SgtPooki** [comment]
@lonnietc It sounds like you want an interface to your nodes.

You can access {nodeIp}:{nodePort}/webui for any Kubo node to access the stats. 

@SvenDowideit, you can probably set up what you like with ipfs/kubo, where you have one private and internal node and another public node. 

We have yet to make any current plans to support separating private/public data in IPFS-Desktop, but if [Kubo](https://github.com/ipfs/kubo) implements some feature for accomplishing this, then I think we could

If you have further questions about what you're trying to do, I recommend searching around on discuss.ipfs.tech or posting your questions, where you can receive more help from various users on our forums.
