### ISSUE TITLE
Location data pull?

### ISSUE THREAD

**Issue by lonnietc** [ipfs/ipfs-desktop#1926]
Hello,

I just started using IPFS-Desktop and tested it on the Public IPFS node for which it works great and showed many peers connected to my local node.

Now, I just setup a Private IPFS network, but the IPFS-Desktop explorer shows "unknown" for the locations and the only real change besides the bootstrap nodes was the inclusion of the "swarm.key" file in my ./ipfs to limit which nodes can connect to the private network.

How does it pull the location information as I would like to have it show the locations of my private nodes if possible.

Thanks and have a great day,

**Comment by hacdias** [comment]
Hey @lonnietc,

IPFS Desktop, or rather, IPFS Web UI, uses [`ipfs-geoip`](https://github.com/ipfs-shipyard/ipfs-geoip) to fetch locations, which are then cached. This data comes from a known hash:

https://github.com/ipfs-shipyard/ipfs-geoip/blob/7ccf13efc5569725b2103d1b1b305bdd23d8e293/src/lookup.js#L11

If your node does not have access to the "outside" network, it won't be able to fetch the data. What you can do, is to either temporarily connect the node to the public network and pin the CID, or download the CID's contents and add it to your node.
