### ISSUE TITLE
ipfs-desktop debian variant fails to load

### ISSUE THREAD

**Issue by jesus-eff** [ipfs/ipfs-desktop#1928]
- OS: Linux (PureOS 9 debian variant)
 - Version of IPFS Desktop 0.17.0

**Describe the bug**
AppImage, deb package and source fail to run on my OS

**To Reproduce**
1. Download app image
2. `chmod a+x ~/Downloads/ipfs-desktop*`
3. try to run: `The futex facility returned an unexpected error code.`
4. Download .deb
5. `dpkg install ~/Downloads/ipfs-desktop*deb`
6. `ipfs-desktop`: `The futex facility returned an unexpected error code.`
7. `git clone https://github.com/ipfs/ipfs-desktop`
8. `cd ipfs-desktop`
9. `npm ci`
10. `npm run build`
11. `npm start`

    > ipfs-desktop@0.17.0 start
    > cross-env NODE_ENV=development electron .
    2021-11-16T22:26:24.427Z info: [meta] logs can be found on /home/jesus_eff/.config/IPFS Desktop
    The futex facility returned an unexpected error code.
    /home/jesus_eff/devel/ipfs-desktop/node_modules/electron/dist/electron exited with signal SIGABRT

**Expected behavior**
The app to start

No logs to attach, it seems the app fails to generate any

    $ ls -a ~/.config/IPFS\ Desktop/
    .  ..  config.json  Dictionaries  SingletonCookie  SingletonLock  SS

**Comment by lidel** [comment]
It sounds like a problem with Electron (https://github.com/electron/electron/issues/24211).

@jesus-eff  are you able to try workarounds from  https://github.com/iotaledger/firefly/issues/1098#issuecomment-845177239 and https://github.com/electron/electron/issues/24211 and see if any of them made it work for you?

If not, the best we can do is bump electron version and see if the problem goes away.

**Comment by jesus-eff** [comment]
electron's strange choice of suppressing logging unless there's an env var... interesting.
once i enabled logging, i saw that it cannot connect to the x display
so, this was user error... derp
thx for the assist
