### ISSUE TITLE
IPFS download notifications (on Mac Client) - cannot tell if it is normal or security compromised

### ISSUE THREAD

**Issue by ChungMasterFlex** [ipfs/ipfs-desktop#1930]
- OS: [macOS Catalina: 10.15.7 ]
 - Version of IPFS Desktop [0.17.0]
 - https://github.com/ipfs/ipfs-desktop/releases/tag/v0.17.0

**Describe the bug**
After using IPFS for about an hour, there is a download warning which I pressed YES to.  (I've accepted twice) assuming it was part of the give and take of being part of the IPFS network.  However, I cannot see the download once I look in my Downloads folder.  (I looked in finder and Terminal to look for hidden files).

Worried now that this is a compromise.

Here is a partial screenshot I took the second time.

![Save As QmdeN2DUDmikJSumJ1JFftwTxUfDJZtf](https://user-images.githubusercontent.com/200106/142903799-946efe9d-2219-49e5-9231-1b482196280d.png)

**To Reproduce**
1. Download IPFS client (I uploaded an image and pinned it in the files tab).
2. Minimize application
3. Wait an hour
4. IPFS, on bottom menu bar, will start bounding indicating a notification
5. Click on IPFS on bottom menu bar
4. Notification to save file in Downloads folder will appear (see above partial screenshot)

NOTE: I am realizing while looking at the screenshot of the download notification that the download file name (at least the first unobstructed portion in view) matches the CID of the file.  Here is the photo within my IPFS client (note the CID name):
![image](https://user-images.githubusercontent.com/200106/142906122-62636e48-1cf8-447a-b781-b62db889884b.png). 

**Expected behavior**
I expected this to happen in the background? Or some clear notification that this is very normal and expected behavior.

**Screenshots**
Screenshots above.

**Additional context**

[combined.log](https://github.com/ipfs/ipfs-desktop/files/7583034/combined.log)
Error.log (is empty and will not be upload by github)

**Comment by rigan0707** [comment]
Duplicate of #

**Comment by lidel** [comment]
@ChungMasterFlex bit confused, mind providing more details?
- were  you using the quick download feature (`Download...` from the IPFS logo menu)? 
- did you import `HelloWorld.png` using IPFS Desktop or was this not something you ever did?

**Comment by ChungMasterFlex** [comment]
- were you using the quick download feature (Download... from the IPFS
   logo menu)?

I didn't do anything special meaning I didn't use the "quick download
feature".  This popup actually appeared when the program was in the
background (I had moved on and done something else) and the IPFS app logo
was bouncing in my Mac tray.  When I clicked on the app on my Mac tray (on
the bottom) it then re-focused on app, then the pop-up appeared for the
download.


   - did you import HelloWorld.png using IPFS Desktop or was this not
   something you ever did?

Yes, the HelloWorld.png (was mine!). I took a screenshot of something,
renamed to HelloWorld.png and then dragged it from finder to IPFS console.
About an hour or so later - I pressed "pin" to the right of the file.  Then
maybe 30 mins or 1 hr later the "pop-up" behavior started.

**Comment by ChungMasterFlex** [comment]
Maybe another way I can ask the question -- how, if at all possible, can you get the IPFS application on Mac to trigger a download notification (to prompt user to download something onto Mac/Finder)?

**Comment by lidel** [comment]
Sure, Electron app can control various elements of macOS interface (ipfs-desktop adds menubar icon, publishes OS-level notifications when you drag-and-drop on them etc). 

I fail to see what is the security issue here. My understanding is that you imported a file to Files screen and some time later got download notification from macOS for the same file.  

-  Are you able to reproduce this every time? 
   If not, it looks like some sort of ux glitch (eg. Electron trying to download image instead of rendering it).

**Comment by ChungMasterFlex** [comment]
Thank you for your response.

The potential security issue is having unprompted downloads (which I’ve
accepted twice).  However - if this is normal of course not an issue. If
this is completely normal/expected behavior - then I am relieved.

However - it asked to download a file and then the file was subsequently
not in my downloads folder. This happened twice.

Without better understanding the system - it seems risky to me to continue
to experimenting if it continues to happen.

> Just to clarify to the scenario in your last comment a I uploaded a file
and it rendered fine in the UI and gave me and identifier for the file and
everything.  The behavior I am writing about happened after maybe 20 mins -
1 hr (during this 20 mins - 1 hr the IPFS client was in the background).

**Comment by hacdias** [comment]
@ChungMasterFlex the download popup is triggered by Shift+Command+H. Is it possible that you're using that key combination with some other software?

**Comment by ChungMasterFlex** [comment]
Interesting … I will have to thing about it. I think I was not pressing
that combo - but it is somewhat reassuring to know that there is a “valid
path” for the download popup.

**Comment by lidel** [comment]
@ChungMasterFlex are you able to update to the [latest version](https://github.com/ipfs/ipfs-desktop/releases/latest) and see is the issue is still present?
