### ISSUE TITLE
IPFS/IPNS Timing Out

### ISSUE THREAD

**Issue by petercottonmouth** [ipfs/ipfs-desktop#1933]
I'm new to IPFS. I created an IPNS and uploaded about 3000 files to a folder from the IPFS desktop app. I took the CID of that folder and updated my IPNS with it. I keep trying to access the data from the URL: "https://gateway.ipfs.io/ipns/" with my IPNS at the end but the connection always times out every time. Did I install it incorrectly? I'm not sure why I can't access the data regardless of the PC/network. I've tried resetting my router, clearing my cache, accessing from my phone with cellular data only turned on.. nothing works. Please help! Any guidance would be greatly appreciated.

**Comment by lidel** [comment]
@petercottonmouth 
It is possible that you are behind a restrictive NAT and gateway is unable to fetch data from you.
Consider:
- enabling uPnP on your router (or asking your ISP to do that for you)
- asking your ISP if they do any p2p filtering – some (eg. Orange) are known to run thin "firewall" for new clients, but it can be disabled


I'm closing this, as we use GitHub only for actionable bugs and future requests. 
In the future please use https://discuss.ipfs.io if you need general support like this, there are more people there who can answer your questions faster :)
