### ISSUE TITLE
IPFS Desktop killed my internet connection

### ISSUE THREAD

**Issue by GalacticPrez** [ipfs/ipfs-desktop#1939]
- OS: Win10
 - Version of IPFS Desktop: 0.17.0
 - 

**Describe the bug**
I installed the desktop application, and in no time at all my internet was down, including the modem/router not being able to connect to the internet ( so I had to reboot it ), and not even mobile devices could connect to the internet via the wifi

**To Reproduce**
no idea at all, but I could try to reproduce it for you another day if it would help ... the problem is I have to keep the internet running for my housemate, so I just had to solve the problem ASAP without paying much attention to what had happened, and I had no idea how to diagnose the cause anyway, so I would probably need your help to do it in such a way as I could generate some files to send to you so that you can diagnose the cause

**Expected behavior**
Well, anything but what happened - it did seem to be getting some IPFS data at first, but then the internet just died from all other respects

**Screenshots**
none taken

**Additional context**
It's possible this has something to do with the fact that IPv6 is being used, perhaps I need to make changes in my network configuration ... at present I have a tplink modem connecting via a single cable to an unmanaged switch, then via another cable to a QNAP NAS, there's another cable between the unmanaged switch and a managed switch ( but I am just learning about this, so it's possible the switch configuration wasn't able to cope with whatever happened once the IPFS application started ), and the NAS connects via 2 cables to the unmanaged switch, and via another 2 ( link aggregated ) to the managed switch, with several end devices plugged into the unmanaged switch, and another few plugged into the managed switch ... they're all on the same VLAN from the modem through to the end devices directly connected to the unmanaged switch, and the modem to the NAS, but I haven't configured a VLAN on the managed switch ( i dont understand enough yet about when and why a VLAN is created - but it works the way I have it, not including this issue ) ... I just rely on the switches to figure stuff out, so the managed switch doesn't have much set up beyond the link aggregation of 2 ports to 2 ports link aggregated on the NAS ... the device I installed the IPFS desktop application to was my newer laptop, which is connected directly to the managed switch, so from its perspective, it has pathways to the modem either via the NAS, or bypassing the NAS, and this is so that I can switch off the managed switch, and simply relocate one cable to remain connected to the internet ( because it's all in my bedroom and rather noisy if I want to sleep ).

I know that probably sounds like a mess to someone who understands what they're doing, but the only way I am going to learn about these things is by having equipment on which I can actually play with it, and I am trying to get to the point where I can play with stuff that doesn't affect my housemate or any other devices connected in the house, as my housemate runs a business from home, so she needs the internet to be stable ... but the only way I can get everything connected without buying more devices and cables ( and I have already spent a lot ), is to use the managed switch to reach the back corner of my room where my desk laptops and servers are located ... hence there isn't much I can do about it other than gradually learning how to set this up so that such problems don't occur ... mind you, I am only guessing that my network setup might have something to do with it ... I just wasn't expecting that the software would do something so dramatic that even the modem got itself disconnected from the internet

If you want me to run a test to reproduce and diagnose the issue, just email me directly: **galacticpresident@me.com** - and I will plan to do it on a day where my housemate is away, so I have plenty of time to fix anything that happens before she gets back.

**Comment by SgtPooki** [comment]
@GalacticPrez I can understand the stress that internet failure can cause. Apologies for your trouble, and thank you for bringing this to our attention :)

Unfortunately, this problem is not unique to you, but it is also not something that is specific to ipfs-desktop. The issue of ipfs killing routers is being discussed at ipfs/go-ipfs#3320. [ipfs/go-ipfs](https://github.com/ipfs/go-ipfs) is the daemon that run behinds the scenes of the ipfs-desktop, which is responsible for all of the network traffic that resulted in your router dying. 

There seem to be a few different solutions, none of which I have looked into, but the last comment (https://github.com/ipfs/go-ipfs/issues/3320#issuecomment-1010573738) has some configuration you may be able to apply to resolve your issue.

Please follow ipfs/go-ipfs#3320 for any updates or further discussion with this issue and good luck!

**Comment by lidel** [comment]
@GalacticPrez on top of that, two quick things you can try:
1. Update to the [latest version](https://github.com/ipfs/ipfs-desktop/releases/latest) (you seem to run 0.17, but the latest one is 0.19+)
    - Not sure if related, but there was a bizzare mDNS bug which crashed dome printers (https://github.com/ipfs/go-ipfs/issues/8534), it is fixed in the latest version.
2. As suggested above, inspect connection limit numbers in [`SwarmConnMgr`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmconnmgr) config. To make this more, actionable, make sure your values are not higher than these  [Desktop defaults](https://github.com/ipfs/ipfs-desktop/blob/a246daa918febc2db9100fc57f07d48ba36fd300/src/daemon/config.js#L49-L51).
