### ISSUE TITLE
Shouldn't be hole punching and relay client be on by default?

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1946]
- OS: Windows
 - Version of IPFS Desktop 0.18.1

**Describe the bug**
I noticed that hole punching and relay client functions are off by default. Shouldn't they be on?

**To Reproduce**
1. Start IPFS Desktop
2. Go to settings

How the config snipped should look like:
```
		"EnableHolePunching": true,
		"RelayClient": {
			"Enabled": true
		},
```

How it looks like by default:

```
		"RelayClient": {	},
```

While the [docs](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmrelayclientenabled) state that RelayClient is off by default and Hole Punching needs Relay Client to work.

**Comment by lidel** [comment]
Relays V2 are new to public swarm, afaik we are waiting for more peers to update, so there are more relays available before we flip the switch in go-ipfs itself.

1. go-ipfs 0.11 ships with service enabled by default (when node detects knows it's publicly diallable)
2. future version, eg. ~go-ipfs 0.12/13 ships with hole punching enabled by default 

We probably don't want to write custom config migration in ipfs-desktop (and Brave) if we will flip it to be implicitly enabled in next go-ipfs anyway.  

@mxinden @marten-seemann  @aschmahmann  when are we enabling RelayClient and hole punching? go-ipfs 0.12?

**Comment by RubenKelevra** [comment]
I just noticed that my client's content couldn't be reached with the default config, had modified it previously to always use the old relay function for incoming connections.

Is the old stuff now gone? 🤔 

I have CGNAT plus local NAT for IPv4 and IPv6 with firewall by the carrier which blocks incoming connections (Yay!). So one if the worst network setups possible I guess 😉

Enabling the options described above fixed my incoming connection issue.

---

Is there a short how-to for "joining"? I saw sll the options and while they are described properly I couldn't find a best practice guide or something like that. Would like to join :)

**Comment by RubenKelevra** [comment]
> 1. go-ipfs 0.11 ships with service enabled by default (when node detects knows it's publicly diallable), network slowly upgrades, we get a healthy set of  relays

I thought relaying traffic is more like a manual switch to be flipped, so we get a set of high power, high bandwidth machines which run 24/7 not random nodes into the service. :)

**Comment by marten-seemann** [comment]
> @mxinden @marten-seemann @aschmahmann when are we enabling RelayClient and hole punching? go-ipfs 0.12?

We still don't have quite enough relays on the network yet, but we're getting close. Given that the rc of go-ipfs v0.12 has already shipped, we probably won't enable it in the final version. v0.13 looks like a more realistic target.

**Comment by lidel** [comment]
go-ipfs PR to enable it by default: https://github.com/ipfs/go-ipfs/pull/8748

**Comment by lidel** [comment]
Hole punching will be enabled by default in 0.13, so ipfs-desktop will get it "for free" when upgrading.

(note: 0.13-rc1 has a bug which we fixed in https://github.com/ipfs/go-ipfs/pull/8966)

**Comment by SgtPooki** [comment]
@ValeZAA yes they should be enabled by default now and this comes from Kubo, so we have no control over this on our side AFAIK.
