### ISSUE TITLE
No "Import Button" at Files tab

### ISSUE THREAD

**Issue by Dentrax** [ipfs/ipfs-desktop#1963]
- OS: `macOS 12`
 - Version of IPFS Desktop `0.18.1`

**Describe the bug**
It says `No files here yet! Add files to your local IPFS node by clicking the **Import** button above.` But there is no import button.

We should wait approx ~5 min to find the files to be able to see "Import" button.

**To Reproduce**
1. Go to "Files" tab
2. See the warning

**Expected behavior**
There should be an "Import button"?

**Screenshots**
<img width="1262" alt="Screen Shot 2022-01-26 at 13 42 19" src="https://user-images.githubusercontent.com/16493751/151149056-fbb3691a-2f10-4254-be60-db979469c65e.png">

**Comment by rigan0707** [comment]
@Dentrax

**Comment by lidel** [comment]
> We should wait approx ~5 min to find the files to be able to see "Import" button.

- Mind rephrasing this? Do you mean that the button appears correctly after a long (5 minutes) wait?
- Do you have a lot of files, or is this a clean install?
- Are you using local node, or did anything custom to talk to remote one over HTTP?

**Comment by Dentrax** [comment]
> Do you mean that the button appears correctly after a long (5 minutes) wait?

Approximately, yes. I had to wait a few minutes to see that button.

> Do you have a lot of files

Fresh installed. Cleaned `~/.ipfs` folder.

> Did anything custom to talk to remote one over HTTP?

Remote talk with Pinata Gateway.

**Comment by lidel** [comment]
@Dentrax Pinta started heavy rate-limiting nand we improved the way remote pins are handled in recent release – are you able to update to ipfs-desktop >0.20.3 and see if situation improved?
