### ISSUE TITLE
IPFS Windows Desktop - No Link to Advanced Features

### ISSUE THREAD

**Issue by ContactJake** [ipfs/ipfs-desktop#1964]
Hey guys,

The Windows version of the IPFS Desktop doesn't seem to have any way of connecting to the advanced features etc.
Specifically I'm unable to perform "Garbage Collection", which I why this came to my attention... (screenshot attached)

Thanks kindly,

J.

![IPFS Issue](https://user-images.githubusercontent.com/98520160/151350624-0f876994-42b7-46dd-aac5-a1bfd2ff65a5.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hacdias** [comment]
Hi @ContactJake! When you say "Advanced Features", I assume you're looking for the advanced features in the menubar that includes the garbage collection running. You should right click on the IPFS Desktop icon in the tray area and then find the desired option under "Advanced":

![image](https://user-images.githubusercontent.com/5447088/151552299-ca3561ec-6faf-465a-96fd-c78077d6f1da.png)

Does that help?
