### ISSUE TITLE
Downloads in Readme are outdated

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1971]
The current downloads listed in the [install](https://github.com/ipfs/ipfs-desktop#install) section of the readme are version 0.17 while the current version is 0.18.1.

I think we should not link specific versions here, but link to the release list on Github.

**Comment by lidel** [comment]
iiuc the automation this was kept open for exists. Every release PR now rewrites the download links itself, through `@ipfs-shipyard/release-please-ipfs-plugin` declared in `release-please-config.json` and wired up in #2664 (v0.32.0). The v0.50.0 release commit b8249ff shows it rewriting the whole Install section.

Closing. If a release ever lands with stale links in the README, please open a new issue.
