### ISSUE TITLE
Add missing libappindicator dependency to readme.md

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1972]
@lidel wrote:

> in theory ipfs-desktop dependencies are the same as any other Electron app, only caveat being libappindicator for tray icon.

_Originally posted by @lidel in https://github.com/ipfs/ipfs-desktop/issues/1890#issuecomment-1030441346_

Looks like this dependency is missing in the readme :)

**Comment by lidel** [comment]
We do have a note here https://github.com/ipfs/ipfs-desktop/#why-am-i-missing-the-system-tray-menu-on-linux

**Comment by lidel** [comment]
Also, I meant that Electron apps not always use tray (which is pandora's box if you want to have it across all operating systems). 

Context:  
* Tray support on modern linux DE is severely broken (https://github.com/ipfs/ipfs-desktop/issues/1153#issuecomment-596780147) 
* Then it got even worse when Chromium switched to StatusIndicator and Electron shipped that change without considering ecosystem consequences 
* Then Electron reverted that decision (https://github.com/ipfs/ipfs-desktop/issues/1153#issuecomment-667129165)

:see_no_evil:
