### ISSUE TITLE
Arch: [0.19.x] New libxcrypt-compat dependency

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#1988]
- OS: Linux
 - Version of IPFS Desktop 0.19.x

**Describe the bug**
After reports that building isn't possible anymore (which I couldn't confirm on the one test machine) I had to add a compat version of libxcrypt.

Previously the regular version of libxcrypt was enough to build it.

_Not sure if this is a new dependency of ipfs-desktop (and it's dependencies) or if this is a change by libxcrypt._

Is there a way to modify ipfs-desktop to remove the need for a compat version of libxcrypt?

[My changes to the dependencies](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=ipfs-desktop&id=31b876b1a5653b18a3e0986d99404e729b0b1d6b).

[The discussion](https://aur.archlinux.org/packages/ipfs-desktop).

**To Reproduce**
1. Build the package without libxcrypt-compat
2. See error

**Expected behavior**
IPFS-Desktop should build without having to rely on compat versions.

**Log**
build error

⨯ cannot execute cause=exit status 127 errorOut=/home/user/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

**Comment by lidel** [comment]
Dependencies of Linux packages are set automatically by `electron-builder`.

This sounds like AUR/Arch problem: 
* https://aur.archlinux.org/packages/signal-desktop-beta#comment-853115
* https://bugs.archlinux.org/task/73799

**Comment by RubenKelevra** [comment]
I thought that's just limited to closed source software. But it looks like that quite a lot software is using it.

They moved libxcrypt-compat to the core repo. So I'm now comfortable to have this as a dependency. :)
