### ISSUE TITLE
[gui error report]

### ISSUE THREAD

**Issue by Jsn2win** [ipfs/ipfs-desktop#1993]
Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.18.1
- **Electron Version**: 13.6.3
- **Chrome Version**: 91.0.4472.164

**Error**

```
Error: No application in the Launch Services database matches the input criteria.
```

**Comment by lidel** [comment]
Please follow instructions from https://github.com/ipfs/ipfs-desktop/issues/1980
