### ISSUE TITLE
Clicking on notification after "Add to IPFS"   on Windows does nothing

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#1999]
"Add to IPFS" via context menu in Explorer on MS Windows 11  imports files to IPFS, and displays the notification, but clicking on notification does not open _Files_ screen (if the WebUI window is closed/hidden).  Nothing happens.

But if I manually open _Files_, the imported data is there.

@hacdias are you able to reproduce this? not sure if this is my machine or if we have a small regression.

**Comment by hacdias** [comment]
Just installed a Window 11 VM. Cannot reproduce on macOS. On Windows 11, I can only reproduce if the notification was initially ignored and is now sitting in the notifications center. When clicking directly after popping up, it works.

**Comment by hacdias** [comment]
I think this already happened in Windows 10: https://github.com/electron/electron/issues/29461

**Comment by lidel** [comment]
Thanks! I think this is more or less blocked by upstream bugs, and since we copy link to clipboard, it is better to just remove "click here" from the notification :^))

https://github.com/ipfs/ipfs-desktop/pull/2013 should remove the problem without us having to spend any more time on this.
