### ISSUE TITLE
Installation under Debian 11 (void link)

### ISSUE THREAD

**Issue by GreenLunar** [ipfs/ipfs-desktop#2015]
Hello, 

I'm attempting to install IPFS Desktop for Debian, following [these instructions](https://github.com/ipfs/ipfs-desktop#why-cant-i-install-ipfs-desktop-under-debian-11).

> Use [this workaround](https://github.com/Clansty/Icalingua/issues/162#issuecomment-899255738) for now.

The above link, is void.

Please advise.
Thank you

**Comment by hacdias** [comment]
Yeah, it seems the repository of that issue was deleted / is private now. I can't find a copy on the Internet Archive. @lidel do you remember what the issue was about?

**Comment by GreenLunar** [comment]
I don't know.

Eventualy, I've downloaded the `.deb` file provided by the IPFS project and it worked.
