### ISSUE TITLE
macOS 10.x fails to start with Error (no message)

### ISSUE THREAD

**Issue by lfnpcsoft** [ipfs/ipfs-desktop#2038]
I opened IPFS Desktop when a windows jumps out reading "IPFS node has encountered an error and startup could not be completed:" and macOS also tells me the application has some problems. 

How to solve?

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.20.2
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error
    at errorTemplate (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:158:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:174:17)
    at async startIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:46:17)
    at async restartIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:100:5)
    at async Object.restartIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:33:5)
```

![Window Picture](https://user-images.githubusercontent.com/90073364/158522704-edd5b61a-430b-493a-a671-3389631a9837.png)

**Comment by lidel** [comment]
@lfnpcsoft you mentioned  "macOS also tells me the application has some problems."  – mind providing more details?
A  screenshot or `combined.log` would be fantastic :pray:

**Comment by lidel** [comment]
https://github.com/ipfs/ipfs-desktop/issues/2056#issuecomment-1075414297 mentions macOS v10.14.6 (Mojave)
Would be good to confirm that other people experiencing the problem are running the same version.

**Comment by lidel** [comment]
https://github.com/ipfs/ipfs-desktop/issues/2040#issuecomment-1074890304 mentions problem occurring after reinstall:
> this is an error I got after I updated ipfs desktop on mac. This is excatly what I did; I deleted ipfs and re downloaded and reinstalled. Upon attempting to launch the error appears

@LordWilliamsr mind providing more info on this?
1. were you reinstalling the same version, or a different one? which?
2. was it an upgrade or a downgrade? 
3. did you remove `.ipfs` (`IPFS_PATH` dir) or kept it? (if you dont know, means you kept it)

**Comment by LordWilliamsr** [comment]
I was reinstalling a newer version for mac 0.20.3
This was an upgrade
I did not remove .ipfs

**Comment by lidel** [comment]
@SgtPooki @hacdias do you have an older macOS box (10.x) at hand to test this?
I was not able to reproduce, all migrations run smooth on my mac mini with macOS 12.x – I have no other machine for tests.

**Comment by hacdias** [comment]
@lidel I also don't have older macOS versions. It also works here.

**Comment by lidel** [comment]
I've run our basic end-to-end tests on `macos-10.15` (https://github.com/ipfs/ipfs-desktop/pull/2063) but it passed fine.

Empty terminal means the logs are never updated in variable here:

https://github.com/ipfs/ipfs-desktop/blob/34a1c48b8ec3030981c5e3afefd5a505e6232bc7/src/daemon/daemon.js#L94

The migration console window is opened with `isErrored=true`  at some point, which suggests we should add some debugging around  [isSpawnedDaemonDead](https://github.com/ipfs/ipfs-desktop/blob/34a1c48b8ec3030981c5e3afefd5a505e6232bc7/src/daemon/daemon.js#L96) – either this check is broken on macOS 10.x OR it works fine, but our daemon fails to start without producing any error (or it does not get passed by js-ipfsd-ctl in time).

## Ask for help: anyone with macOS 10.x and 5min of spare time?

A useful test would be to install [command line](https://docs.ipfs.io/install/command-line/#macos) on macOS 10.x and see if `ipfs daemon` started in a terminal runs fine (or not). This will inform our next steps.

**Comment by sd70mac** [comment]
> I've run our basic end-to-end tests on `macos-10.15` (#2063) but it passed fine.
> 
> Empty terminal means the logs are never updated in variable here:
> 
> https://github.com/ipfs/ipfs-desktop/blob/34a1c48b8ec3030981c5e3afefd5a505e6232bc7/src/daemon/daemon.js#L94
> 
> The migration console window is opened with `isErrored=true` at some point, which suggests we should add some debugging around [isSpawnedDaemonDead](https://github.com/ipfs/ipfs-desktop/blob/34a1c48b8ec3030981c5e3afefd5a505e6232bc7/src/daemon/daemon.js#L96) – either this check is broken on macOS 10.x OR it works fine, but our daemon fails to start without producing any error (or it does not get passed by js-ipfsd-ctl in time).
> 
> ## Ask for help: anyone with macOS 10.x and 5min of spare time?
> Someone experiencing this error could install [command line](https://docs.ipfs.io/install/command-line/#macos) on macOS 10.x and see if `ipfs daemon` started manually in a terminal runs fine (or not).
> 
> The output of this test this will inform our next steps.

I just tried `ipfs daemon` and after it reaches the line `Daemon is ready` it gives error messages of the type `2022-03-23T22:17:19.667-0500	ERROR	tcp-tpt	go-tcp-transport@v0.4.0/tcp.go:52	failed to enable TCP keepalive	{"error": "set tcp4 192.168.2.216:4001->195.206.185.205:4001: setsockopt: invalid argument"}
`.  The IP addresses change in the second field (i.e.`195.206.185.205:4001`) change, but the errors are otherwise identical to each other.  I can provide more output if you really want.

**Comment by mlgx** [comment]
I'm on 10.15.7 and I have the same issue with versions 0.19.1 and 0.20.3.
Versions 0.18.1 and 0.17.0 work fine. Go-ipfs 0.12.0 also works.
Removing .ipfs and .ipfs-desktop folders doesn't help.

Here is a complete crash report: https://gist.github.com/mlgx/c4b984046a03b1597fd8609274f1eae7

IPFS-Desktop should not force updates. It makes reverting to an older version impossible.

**Comment by lidel** [comment]
Thank you all, this is really useful. Seems that there is a problem where Electron (ipfs-desktop) spawns go-ipfs:

```
2022-03-23T13:56:45.028Z error: [ipfsd] start daemon Error:  

  

 Command was killed with SIGSEGV (Segmentation fault): /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs daemon --agent-version-suffix=desktop --migrate --enable-gc --routing=dhtclient 


    at makeError (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
crashed on child side of fork pre-exec
```

My gut feeling would be Electron bug, or that the binary at `/Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs` is corrupted, but we would have to confirm that.

@MattJohnsonMusic @mlgx  Would it be possible for you to upload that file somewhere, so we can compare sha512 checksums, just to confirm/refute this hypothesis?

**Comment by MattJohnsonMusic** [comment]
I think this is what you asked for. Let me know if not.
[ipfs.zip](https://github.com/ipfs/ipfs-desktop/files/8352179/ipfs.zip)

**Comment by lidel** [comment]
Yeah, checksum is different:

```
$ sha512sum ipfs 
94fb7e85a893a28083ebdeca974394b134ddf43ca43babe6be490c1f1f59f32c64424b330f9ed128bc9d64a7b72cf42a8104e4f62c73e0367dd406f5b28458f1


$ sha512sum go-ipfs/ipfs # from go-ipfs_v0.12.0_darwin-amd64.tar.gz
6b9aae97dc9c54476092ebb84644980e9c353a97187ee0e22e3b7c9c30cdd5676993cc4dc9786ac732ff1f91bc6475abffdefce1a58cfdd1336125d7787e4c94
```

@MattJohnsonMusic  are you able to download  https://dist.ipfs.io/go-ipfs/v0.12.0/go-ipfs_v0.12.0_darwin-amd64.tar.gz, unpack it and replace your broken `ipfs` with one from  `go-ipfs/ipfs` in that `.tar.gz` ?

**Comment by MattJohnsonMusic** [comment]
Forgive my ignorance, but have downloaded/expanded, now exactly WHAT line of code should I run in Terminal??

**Comment by MattJohnsonMusic** [comment]
(not dumb, just not Terminal savvy. If we wanna talk music, I'm good to go. Just don't speak computer coding as well…at all)

**Comment by lidel** [comment]
@MattJohnsonMusic the idea is to replace (override) corrupted `/Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs` with valid one  which ins inside https://dist.ipfs.io/go-ipfs/v0.12.0/go-ipfs_v0.12.0_darwin-amd64.tar.gz archive and see if that fixes the problem. 

I think you should be able to do that with Finder, but you can also do it in Terminal.
Sadly  I dont use macOS so dont know exact commands for it, but it would be along these lines:


1. Rename broken binary:
`mv /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs.broken`

2. Go to the directory where you downloaded https://dist.ipfs.io/go-ipfs/v0.12.0/go-ipfs_v0.12.0_darwin-amd64.tar.gz and unpack it:
`tar xvf go-ipfs_v0.12.0_darwin-amd64.tar.gz`

3. Copy new binary in correct place:
  `cp go-ipfs/ipfs /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs`

**Comment by MattJohnsonMusic** [comment]
Hello, SO…tried lidel's suggestion (above) to replace/copy over files. Either didn't work, or I didn't do things correctly. Finally, just GAVE UP!

• Dragged out another (older) iMac with no IPFS app history. Installed IPFS Desktop app and CRASHED. So, it's definitely something the new app software doesn't like with macOS High Sierra.
• Finally, used wife's newer Mac Airbook, running Big Sur. Upgraded macOS to Monterey v12.3. Installed IPFS Desktop app. Had to install "Rosetta" to make work (whatever). Restarted computer, opened IPFS Desktop and…CRASHED. (Jeez, really?)
• IPFS Desktop auto restarted and then seemed to work fine. FINALLY. Uploaded some files...whew, crisis averted. Just a major hassle and work-around to get the simple concept/idea of making IPFS easier to access through a desktop app.
••HOWEVER, each time I open IPFS Desktop app, it initially crashes, then resets itself. Can't imaging that's normal, but I'm holding my breath and just trying to upload my files before it doesn't work at all.

Problem still exists, but I've figured out a work-around for my IPFS needs…until I buy a nice, new, shiny computer later in the year.
Thanks to ALL for your help along the way,
M

**Comment by mlgx** [comment]
<strike>
I ran some tests using IPFS Desktop 0.19.1 since I've established that it's the version that introduced the breaking change.
Replacing `go-ipfs/ipfs` with the one from 0.18.1 or with go-ipfs 0.12.0 does not fix the issue.
The error is the same (segfault).
I also tested IPFS Desktop 0.18.1 with `go-ipfs/ipfs` taken from 0.19.1 and it works fine.
So it's safe to assume that the issue does not come from `go-ipfs/ipfs`.
I also ran from source and narrowed it down to a commit between 80ee282124beeb0e4681d4c49a344ed248e203b8 and a942d4d7737f09f14709a1bc4e34fb037cc27db6. I would need more time to find the exact commit that introduced the breaking change.
</strike>

Version 0.20.4 fixes this!
I should have started there 🤦

**Comment by KEINOS** [comment]
I confirm that **IPFS Desktop v0.20.4 fixed the problem** even for High Sierra! 👍 Amazing job!!!

- IPFS Desktop:
    - Downloaded from latest releases page.
    - IPFS Desktop Version: 0.20.4
    - Agent: `go-ipfs` v0.12.1 desktop
    - UI: `v2.15.0`
- OS:
    - macOS HighSierra (OSX 10.13.6, 17G14042)
- Hardware:
    - Mac mini (Late 2012)
    - CPU: 2.6 GHz Intel Core i7
    - Mem: 16 GB 1600 MHz DDR3
    - GPU: Intel HD Graphics 4000 1536 MB
- Additional info:
    - SHA-512 checksum of `go-ipfs`

        ```shellsession
        $ pwd
        /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs
        $ ls -l
        total 107744
        -rwxr-xr-x@ 1 admin  admin       852  3 18 06:10 install.sh
        -rwxr-xr-x@ 1 admin  admin  55160032  3 28 20:25 ipfs
        $ shasum -a 512 ./ipfs
        347d654304ca0e1e6bbc1e059e93a398c5ff7e6dfd6d058013f52438cd3c734977ea8a271c28f741944a3cf367d8f5b01c1cd5d4e9a8d280b4847443f68f70a1  ./ipfs
        ```

**Comment by lidel** [comment]
@MattJohnsonMusic  try overwriting your old IPFS Desktop app with latest version from https://github.com/ipfs/ipfs-desktop/releases/download/v0.20.4/IPFS-Desktop-0.20.4.dmg 

It seems to solve the problem for others.

**Comment by MattJohnsonMusic** [comment]
Thank you. I downloaded/installed 20.4 and it does seem to work...whew!
Peace, Matt
