### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by freemasonrysquared** [ipfs/ipfs-desktop#2042]
When attempting to upload files to IPFS firstly I can't user $ node utils/nftport/uploadFiles.js because VSCode didn't recognized the "$" but ran without and I get Error [ERR_REQUIRE_ESM]: require() of ES Module. Please help. I coding from 1.1.1 Hashlips from your first video. 

- OS: [e.g. macOS, Windows, Linux]
 - Version of IPFS Desktop [e.g. 0.20.0]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lidel** [comment]
This is repo about ipfs-desktop, please fill issue in appropriate place or ask in https://discuss.ipfs.io/c/help/13
