### ISSUE TITLE
Eror initializing daemon after/during fs-repo-11-to-12

### ISSUE THREAD

**Issue by kidcdf** [ipfs/ipfs-desktop#2066]
just download the lastest version, but can not open ipfs desktop, always downloading...
![image](https://user-images.githubusercontent.com/57767063/159924737-72bec057-5fdb-4bec-babf-eebe4adf4c0b.png)

![image](https://user-images.githubusercontent.com/57767063/159923884-ae40bc2f-ed32-483f-a6ce-0b5358010fb4.png)

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.20.3
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.16.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 2 migrations, downloading.
Downloading migration: fs-repo-10-to-11...
Downloading migration: fs-repo-11-to-12...
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-10-to-11/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-10-to-11/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-10-to-11/versions"
Error fetching: exceeded number of retries. last error was http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-10-to-11/versions": dial tcp 104.16.252.55:443: i/o timeout
Error fetching: exceeded number of re[](url)

**Comment by kidcdf** [comment]
help

**Comment by kidcdf** [comment]
用清理工具彻底删除IPFS APP, 再重装,解决了
solved, delete the app  by clean tool, reinstall

**Comment by lidel** [comment]
@kidcdf we would like to understand what was the underlying problem (sadly the relevant log got  cut-off)

Are you able to send  `combined.log` and `error.log`  from the logs directory? :pray: 
You can open the directory from the tray menu: 

> ![2022-03-28_21-25](https://user-images.githubusercontent.com/157609/160471800-a54f666f-e5d7-4a04-ab1c-037b4d66df5f.png)

Thanks!

**Comment by hacdias** [comment]
Duplicate of #2023
