### ISSUE TITLE
macOS: "Check for Updates > Install Now" does not update

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-desktop#2079]
- OS: macOS
 - Version of IPFS Desktop 0.18.1

**Describe the bug**
My IPFS desktop alerts me to update it multiple times per day, and I click the "update and relaunch" prompt but it never upgrades 

**To Reproduce**
Not sure - for me - just click the button or click "check for upgrades" and IPFS Desktop reboots but doesnt upgrade

**Expected behavior**
IPFS Desktop upgrades and relaunches as expected

**Screenshots**
<img width="343" alt="image" src="https://user-images.githubusercontent.com/618519/160224139-63a896af-6b54-41f1-a449-1faaa8d93fa3.png">

**Additional context**

**Comment by momack2** [comment]
I just uninstalled and reinstalled the 20.2 version of desktop - and the updater here still doesnt work (when I say check for updates --> new update --> install - it stays at version 20.2 instead of migrating to 20.3)

**Comment by momack2** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/618519/160224229-89aa8b52-86db-4795-becb-8bee084267f5.png">

**Comment by lidel** [comment]
macOS autoupdate was broken for 0.19 (details in  #1980), but your reinstall to 0.20.2 should fix it.

Update happens in the background, and you won't see any prompt/notification until new version is fetched correctly. Fetching it on a slower network, or when github has a hiccup, may take time.

If your macOS has notification turned off (and it seems to be the default these days?) you won't see anything, but your node will update the next time you Quit and start it again.

@momack2 are you able to quit+start IPFS Desktop to see if the update got eventually downloaded and applied?

**Comment by lidel** [comment]
Thank you @momack2, this seems to be yet another regression on macOS.

The unfortunate reality is that Electron autoupdate story on macOS still uses the [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) glue and ductape.   Hopefully they will fix this upstream at some point.

We could fix UX of this by removing "Install now" option on macOS, but then we are left with only one way of applying update (on Quit) and if that ALSO breaks (as it did in the past), we will repeat the fiasco from https://github.com/ipfs/ipfs-desktop/issues/1980. 

Keeping it is a lesser evil imo, especially given limited bandwidth we have for this project. 
(Of course if anyone from community has time to debug this, I'm happy to review)

**Comment by lidel** [comment]
I re-tested this as part of QA around security bug fix release [v0.20.5](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.20.5) and got notified about new release and clicking on "Install Now" worked as expected.

@momack2 mind checking if you can update to v0.20.5 without the originally reported problem?

**Comment by momack2** [comment]
Yep! Was able to find and upgrade to the 20.5 release successfully!

**Comment by momack2** [comment]
Sg - agree lesser evil. Thanks for debugging!
