### ISSUE TITLE
Ability to publish with IPNS

### ISSUE THREAD

**Issue by nokemono** [ipfs/ipfs-desktop#2084]
**Is your feature request related to a problem? Please describe.**
ipfs desktop does not have the ability to set ipns.
Without the ability to make a file invisible, it is not usable for practical purposes.

**Describe the solution you'd like**
In FILES, I would like the ability to set ipns.

**Describe alternatives you've considered**
The only alternative, for now, is through the CLI.

**Comment by lidel** [comment]
Thank you for filling this issue.
This is being implemented in https://github.com/ipfs/ipfs-webui/pull/1857

**Comment by lidel** [comment]
Done: https://github.com/ipfs/ipfs-webui/pull/1973
