### ISSUE TITLE
Error: failed: listen tcp4 127.0.0.1:5001: bind: address already in use

### ISSUE THREAD

**Issue by mrheyday** [ipfs/ipfs-desktop#2095]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: linux
- **IPFS Desktop Version**: 0.20.2
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: amd64/linux
Golang version: go1.16.12
2022/04/06 19:16:57 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/192.168.120.68/tcp/4001
Swarm listening on /ip4/192.168.122.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.120.68/tcp/4001
Swarm announcing /ip6/::1/tcp/4001

Error: serveHTTPApi: manet.Listen(/ip4/127.0.0.1/tcp/5001) failed: listen tcp4 127.0.0.1:5001: bind: address already in use

    at errorTemplate (/opt/IPFS Desktop/resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/opt/IPFS Desktop/resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/opt/IPFS Desktop/resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/opt/IPFS Desktop/resources/app.asar/src/daemon/daemon.js:158:9)
    at processTicksAndRejections (node:i

**Comment by hacdias** [comment]
Hi!

It seems that IPFS Desktop failed to detect that something was already running on 5001, or it did and you chose not to change the ports. The error is clear, there is something running on port 5001. Do you perhaps know what it is?

I see you're on Linux, so perhaps running

```
sudo netstat -tulpn | grep LISTEN | grep 5001
```

Will give you information about what is running on that port.

**Comment by KennyDxsale** [comment]
i still have this issue, it happens after i remove the lock files as can be seen in https://github.com/ipfs-inactive/support/issues/12

**Comment by KennyDxsale** [comment]
Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: arm64/darwin
Golang version: go1.16.12

**Comment by SgtPooki** [comment]
@KennyDxsale, Hacdias responded to you previously explaining that this error means you have some port running on 5001. You have to follow the solutions outlined in that error message, and referenced by hacdias as well. i.e. stop the process running on 5001 first, or tell ipfs-desktop to use a different port.

**Comment by nblogist** [comment]
`sudo kill -9 $(sudo lsof -t -i:5001)`

Some processes might be using the port already. Worked for me
