### ISSUE TITLE
IPFS HELP

### ISSUE THREAD

**Issue by jimmynsfw** [ipfs/ipfs-desktop#2105]
Everytime I start up IPFS Desktop I see this message  "Could not connect to the IPFS API" and steps on installing IPFS daemon. I NEED HELP

**Comment by hacdias** [comment]
Hi @jimmynsfw! I'm sorry you are not being able to use IPFS Desktop as you'd hope to. Could you please answer the following questions:

1. What version of IPFS Desktop are you using? Have you used it before?
2. Did you already have an IPFS repository?
3. Can you show us a screenshot of the error?
