### ISSUE TITLE
chore: All `ipcMain.emit` eventNames should be standardized and typed

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-desktop#2115]
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/auto-updater/index.js#L143
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/auto-updater/index.js#L149
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/automatic-gc.js#L28
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/run-gc.js#L33
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/run-gc.js#L66
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/i18n.js#L33
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/daemon/index.js#L17
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/tray.js#L33
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/tray.js#L275
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/tray.js#L276
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/utils/create-toggler.js#L20
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/enable-namesys-pubsub.js#L28
https://github.com/ipfs/ipfs-desktop/blob/d3897337466479ccf23c9fcfa1152d03dfb157ae/src/enable-pubsub.js#L28

_generated with:_
```bash
git fetch --all
git checkout main
git pull
# then...
rg 'ipcMain.emit' src -n -m 999 --no-heading | awk '{print "https://github.com/ipfs/ipfs-desktop/blob/COMMIT_HASH/" $1}' | sed 's/:$//g' | gsed -e 's/:\([0-9]\+\)/#L\1/' -e "s/COMMIT_HASH/$(cat .git/refs/heads/main)/"
```

**Comment by noliveira95** [comment]
#2189
