### ISSUE TITLE
Update transifex translations automatically via github action

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-desktop#2135]
**Is your feature request related to a problem? Please describe.**
Part of the developer notes for releasing a new version of IPFS-desktop indicate that we need to run transifex locally and then push the changes. We should instead run this as part of a release github action
 
**Describe the solution you'd like**
We should use something like https://github.com/marketplace/actions/github-transifex-actions

**Describe alternatives you've considered**
Running transifex locally as specified at https://github.com/ipfs/ipfs-desktop/blame/main/DEVELOPER-NOTES.md#L25

**Additional context**
Enabling this functionality via github actions means we wouldn't have to have devs who need to release a version create a transifex account.
* Related to #1528

**Comment by SgtPooki** [comment]
@lidel , this could use your input whenever you get a chance.

**Comment by lidel** [comment]
Yes, automating i18n would be really nice :+1:  (and we would apply it across all translated projects)

FYSA we already have Transifex set up for fetching source strings once a day (https://www.transifex.com/ipfs/ipfs-desktop/content/ → "Auto update resources"), but we don't have automation for pulling translations back – this is still a manual step done via `tx`  before the release.


- I briefly looked at https://docs.transifex.com/transifex-github-integrations/github-tx-ui  but  afaik it still has the awkward permission model where we need to give Transifex write rights to our repo – I dont feel comfrortable with such broad permission granting to a third-party, so we can't use this.
- Isolated github action you linked, namely https://github.com/sergioisidoro/github-transifex-action#pull-the-entire-current-state-from-transifex-and-commit-to-the-pr with `pull_sources: false` sounds better – PR is created programmatically without granting any special access to Transifex, and we only fetch translations, and dont overwrite source strings.

**Comment by SgtPooki** [comment]
I completely agree with your view on permissions granted to transifex. Alright, I will look into this later thanks for your input!

**Comment by SgtPooki** [comment]
this is done
