### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [ipfs/ipfs-desktop#2138]
**Is your feature request related to a problem? Please describe.**
A easy to install and updatable package on Ubuntu

**Describe the solution you'd like**
A pacstall package. Pacstall is the AUR equivalent for Ubuntu

**Describe alternatives you've considered**
PPA but PPAs are hard to setup and hard to install

**Additional context**
The package is available on the AUR, Adding it on Ubuntu Pacstall makes it easy and secure to install and update IPFS desktop.

**Comment by lidel** [comment]
I am closing this, as adding third-party package managers is not something we have bandwidth for.


Someone from the community needs to create pacstall package and maintain it.
Here are some docs to get you started: https://github.com/pacstall/pacstall/wiki/Pacscript-101



AUR package is maintained by community member @RubenKelevra
