### ISSUE TITLE
Download via IPFS failed

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#2156]
- OS: Linux
- Version of IPFS Desktop *regardless*

**Describe the bug**
This never worked for me, I'm just curious why.

**To Reproduce**
1. Build ipfs-desktop
2. See it fail to fetch the data via the locally running ipfs daemon

**Expected behavior**
Use the ipfs daemon

**Log**
```
> npx ipfs-or-gateway -c bafybeiednzu62vskme5wpoj4bjjikeg3xovfpp4t7vxk5ty2jxdi4mv4bu -p assets/webui/ -t 360000 --verbose

✖ Could not fetch via IPFS.
✔ Fetched bafybeiednzu62vskme5wpoj4bjjikeg3xovfpp4t7vxk5ty2jxdi4mv4bu to assets/webui/!
```

**Additional context**
```console
# netstat -tulpen | grep 5001
tcp        0      0 127.0.0.1:5001          0.0.0.0:*               LISTEN      961        3113442    193463/ipfs         
tcp6       0      0 ::1:5001                :::*                    LISTEN      961        3113443    193463/ipfs       
```

**Comment by hacdias** [comment]
@RubenKelevra is the "Could not fetch via IPFS" immediate or does it take some time to fail downloading via IPFS?  If it's immediate, one possibility is that `ipfs-or-gateway` uses the `ipfs` command in your PATH. IPFS Desktop no longer provides the `ipfs` command line tool with it.

**Comment by hacdias** [comment]
> My ipfs runs under a system user account, so a simple ipfs get would search in the $HOME directory for an .ipfs folder and use this offline instead of using the API.

Maybe add the `IPFS_PATH` environment variable to your system to point at the correct IPFS repository so it gets picked up by the IPFS command line.

I'm closing this issue as it is not related to this repository and it seems to be behaving as expected. The problem here is that you're using a custom IPFS repository location and the `IPFS_PATH` variable isn't set.
