### ISSUE TITLE
[gui error report] TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by ViorelH** [ipfs/ipfs-desktop#2162]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.6
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
TypeError: Object has been destroyed
    at run (E:\Programe Instalate\IPFS Desktop\resources\app.asar\src\index.js:104:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by hacdias** [comment]
Hi @ViorelH! This seems to be a very generic error and I can't really help you with the information provided. Could you just try restarting IPFS Desktop? Do you get the same error?
