### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by ri3tn** [ipfs/ipfs-desktop#2164]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.6
- **Electron Version**: 18.0.3
- **Chrome Version**: 100.0.4896.75

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.2
Repo version: 12
System version: amd64/windows
Golang version: go1.16.15
Error: open C:\Users\Robert Ta\.ipfs\datastore\CURRENT.bak: Access is denied.


    at errorTemplate (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:78:49)
    at Object.loadWindow (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\migration-prompt.js:115:26)
    at startIpfsWithLogs (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:163:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:194:17)
    at async startIpfs (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:46:17)
    at async module.exports (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:114:3)
    at async run (C:\Users\Robert Ta\AppData\Local\Programs\IPFS Desktop\reso

**Comment by ri3tn** [comment]
1. I just installed IPFS
2. Tried uploading one file, it worked
3. 5 minutes later, got this issue
4. Tried restarting computer, running as admin, etc. - doesn't work
5. Now exploring this:https://github.com/ipfs/go-ipfs/issues/3971

**Comment by SgtPooki** [comment]
Hi @ri3tn , thanks for submitting this issue.

The error itself is easy to fix -- simply delete the files with the invalid permissions -- but how we got to that state is a more difficult problem.

When exactly does this error pop up? What is it preventing you from doing? 

I have a few questions to attempt to figure out how the permissions issues began:

1. Can you clarify whether you ran any commands via the command line separately from the IPFS desktop application?
2. Did you run IPFS-desktop as admin when you first started it? (you shouldn't need to run IPFS desktop as admin)
3. If you stop IPFS desktop, delete `C:\Users\Robert Ta\.ipfs\datastore\CURRENT.bak`, and then restart the app, does the error still pop up?

**Comment by ri3tn** [comment]
Hey there, thanks for the help. See my responses below.

**When exactly does this error pop up? What is it preventing you from doing?**
It pops up whenever I start the IPFS desktop app. It's preventing me from checking on files / uploading files. It says it "Could not connect to the IPFS API".

I have a few questions to attempt to figure out how the permissions issues began:

**Can you clarify whether you ran any commands via the command line separately from the IPFS desktop application?
Did you run IPFS-desktop as admin when you first started it? (you shouldn't need to run IPFS desktop as admin)
If you stop IPFS desktop, delete C:\Users\Robert Ta\.ipfs\datastore\CURRENT.bak, and then restart the app, does the error still pop up?**
I did not run any commands via the command line separately from the desktop app. After I got this error, I tried running as admin and saw the same error. I then tried reinstalling the application, and ran into the same error. I tried deleting the CURRENT.bak file, but it is not there. I double checked via terminal (ran admin) and it wasn't there. I then tried to open the app again, and I receive the same error.

**Comment by Twerewolf** [comment]
same problem.


Initializing daemon...
go-ipfs version: 0.13.0
Repo version: 12
System version: amd64/windows
Golang version: go1.18.3

Error: open C:\Users\ubuntu\.ipfs\datastore\CURRENT.bak: Access is denied.

that's all I got, btw my user name is "ubuntu".     :0)

**Comment by Twerewolf** [comment]
您好！您的邮件已收到，我会尽快回复您。谢谢！

**Comment by SgtPooki** [comment]
@ri3tn 

Thanks for the answers, we're very confused by this error but we're going to try to reproduce on our end and will attempt to assist you as best we can. To that effect, here are a few more questions and troubleshooting steps:


1. What windows version are you on? 7/8/10/11?
1. list permissions for the following directories and provide in response:
  * C:\Users\Robert Ta\.ipfs
  * C:\Users\Robert Ta\.ipfs\datastore 
2. check free space available on the C drive
3. run disk scan to ensure disk is fine (check out ttps://neosmart.net/wiki/chkdsk/#How_to_run_CHKDSK_in_Windows) and please provide CLI output, or screenshot of results

**Comment by Twerewolf** [comment]
Initializing daemon...
go-ipfs version: 0.13.0
Repo version: 12
System version: amd64/windows
Golang version: go1.18.3 
@SgtPooki 
ipfs-desktop 0.21.0
