### ISSUE TITLE
countly metrics: Ensure that CI runs of webui/desktop are not emitting metrics to countly

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-desktop#2197]
I am not sure whether CI/CD runs (github actions, etc) are being counted in county currently or not, but I want to make sure that they are not. This issue is intended to track:

1. Checking whether or not metrics are emitting for CI/CD runs (github actions, etc)
2. If they are being emitted, preventing those metrics from being emitted.

**Comment by lidel** [comment]
Our metrics have to remain opt-in, so nothing should be emitted.

**Comment by SgtPooki** [comment]
> Our metrics have to remain opt-in, so nothing should be emitted.

Do we not have a test that confirms the consent form works? If not, we should. If we do, it would emit metrics upon confirming that the form works without work being proposed here. This could probably use some more detailed planning.

**Comment by SgtPooki** [comment]
im just going to close this. we have enough work
