### ISSUE TITLE
libp2p faster than light again

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#2211]
> ![2022-07-21_13-42](https://user-images.githubusercontent.com/157609/180206764-69dd5c21-cb5b-4249-88f6-89e5e6541231.png)

Fix for thix exists in ipfs-webui [v2.16.0](https://github.com/ipfs/ipfs-webui/releases/tag/v2.16.0), which updated geoip dataset, but we are unable to switch to latest webui because of this bug: https://github.com/ipfs/ipfs-webui/issues/1984

**Comment by SgtPooki** [comment]
This should no longer be an issue, and we've updated to the latest webui a while ago
