### ISSUE TITLE
Error: unrecognized routing option

### ISSUE THREAD

**Issue by sintoniza-c** [ipfs/ipfs-desktop#2217]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: darwin
- **IPFS Desktop Version**: 0.22.0
- **Electron Version**: 19.0.8
- **Chrome Version**: 102.0.5005.148

**Error**

```
Error: Initializing daemon...
Kubo version: 0.14.0
Repo version: 12
System version: amd64/darwin
Golang version: go1.18.3

Error: unrecognized routing option: 

    at errorTemplate (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:78:49)
    at loadWindow (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:115:26)
    at module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/migration-prompt.js:120:3)
    at startIpfsWithLogs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:165:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/daemon.js:194:17)
    at async startIpfs (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:47:17)
    at async module.exports (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/daemon/index.js:115:3)
    at async run (/Applications/IPFS Desktop.app/Contents/Resources/app.asar/src/index.js:84:5)
```

**Comment by hacdias** [comment]
Hi @sintoniza-c,

Thanks for reporting this error. I think that your configuration might be outdated or something got lost during some upgrade. Could you please share with us the contents of your `config.json` file? You can access it through two ways:

1. IPFS Desktop Menubar Icon -> Advanced -> Open Configuration File
2. Check [this directory](https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files) for the configuration file.

**Comment by sintoniza-c** [comment]
Hi, I attach the required file 'config.json'
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



29 Jul 2022, 13:51 by ***@***.***:

**Comment by lidel** [comment]
@sintoniza-c it did not work, mind manually attaching it to a comment at https://github.com/ipfs/ipfs-desktop/issues/2217 ?

**Comment by sintoniza-c** [comment]
Okay, I attach the config.json again, this time to this comment in GitHub #2217
Apparently GitHub does not allow for the format .json. I had to convert it to PDF in order to be able to attach it here
[config.pdf](https://github.com/ipfs/ipfs-desktop/files/9242669/config.pdf)
.

**Comment by hacdias** [comment]
Interesting, your flags do not have any routing option. What do you think @lidel?

**Comment by lidel** [comment]
@sintoniza-c are you able to check what is the value of [`Routing.Type`](https://github.com/ipfs/kubo/blob/master/docs/config.md#routingtype)  in your `.ipfs/config` file ? Try changing it to `dht` and let us know if it helped?

**Comment by sintoniza-c** [comment]
What kind of information (so far I supplied the console.json file and informed that the failure for the IPFS desktop app to open coincided with the MacOS update to 12.5)
What else do you need in order to to help me and get IPFS running again (it worked fine for more than 2 years)
Best regards
Chris
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



15 Aug 2022, 02:18 by ***@***.***:

**Comment by hacdias** [comment]
@sintoniza-c, we need the value of the field `Routing.Type` that is located in the `config` file inside your IPFS repository. This repository is usually located at `~/.ipfs`, as @lidel mentioned. Please also try to change the value to `dht`.

If you can't find the repository directory, but IPFS Desktop can still open, try using the menu to open it: `Advanced` -> `Open Repository Directory`.

**Comment by sintoniza-c** [comment]
Thanks for your advice! Changing the value of Routing.Type in the .ipfs/config file did the trick. IPFS desktop opens again.
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



8 Aug 2022, 19:05 by ***@***.***:

**Comment by hacdias** [comment]
Perfect, thanks for the update!

**Comment by sintoniza-c** [comment]
the failure for IPFS desktop app to start happened immediately after updating MacOS to vs. 12.5 about 2 weeks ago.
Chris
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



2 Aug 2022, 15:51 by ***@***.***:
