### ISSUE TITLE
Missing libraries reported by Arch's namcap

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#2218]
- OS: ArchLinux
- Version of IPFS Desktop 0.22.0

**Describe the bug**
`namcap` (a packaging tool) complains about three missing library missing when I build the package on Arch - which is all part of nss (under Arch).

```
ipfs-desktop W: ELF file ('opt/IPFS Desktop/resources/app.asar.unpacked/node_modules/go-ipfs/go-ipfs/ipfs') lacks PIE.
ipfs-desktop E: Dependency nss detected and not included (libraries ['usr/lib/libnss3.so', 'usr/lib/libnssutil3.so', 'usr/lib/libsmime3.so'] needed in files ['opt/IPFS Desktop/ipfs-desktop'])
```

**Comment by lidel** [comment]
iiuc you are building via third-party script in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ipfs-desktop and Arch-specific build  uses [`namcap`](https://wiki.archlinux.org/title/namcap) tool for common packaging mistakes. 

I have to close this as pacman target is not officially supported  (we have no bandwidth to debug distribution-specific quirks),  but you may see why [nss](https://archlinux.org/packages/core/x86_64/nss/) was not pulled-in as a dependency. Could be a bug in Arch, or in  [electron-builder](https://github.com/electron-userland/electron-builder).
