### ISSUE TITLE
[gui error report] TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by Aan09-cyber** [ipfs/ipfs-desktop#2230]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.22.0
- **Electron Version**: 19.0.8
- **Chrome Version**: 102.0.5005.148

**Error**

```
TypeError: Object has been destroyed
    at run (C:\Users\MDM3 XAR\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\index.js:99:19)
```

**Comment by SgtPooki** [comment]
Thanks for submitting this issue @Aan09-cyber. Can you please provide more information about what you were doing when this error occurred, as well as the `combined.log` and `error.log` files?
