### ISSUE TITLE
[gui error report] Error: Cannot move 'C:\Users\Administrator\.ipfs' to a subdirectory of i

### ISSUE THREAD

**Issue by Mlorusso1126** [ipfs/ipfs-desktop#2234]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.22.0
- **Electron Version**: 19.0.8
- **Chrome Version**: 102.0.5005.148

**Error**

```
Error: Cannot move 'C:\Users\Administrator\.ipfs' to a subdirectory of itself, 'C:\Users\Administrator\.ipfs\.ipfs'.
    at C:\Users\Administrator\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\util\stat.js:60:17
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by hacdias** [comment]
It seems you are trying to use the 'Move Repository Location' feature to move the repository to a directory in within itself. That does not make sense. Could you please explain what you were doing when the error happened?

**Comment by lidel** [comment]
Sidenote: it is a very bad idea to run IPFS node as Administrator. You should never run things with admin permissions.

Try uninstalling and reinstalling IPFS Desktop under a regular user (not Administrator).
