### ISSUE TITLE
[gui error report] 

### ISSUE THREAD

**Issue by Mlorusso1126** [ipfs/ipfs-desktop#2242]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.22.0
- **Electron Version**: 19.0.8
- **Chrome Version**: 102.0.5005.148

**Error**

```
Error: ENOENT: no such file or directory, lstat 'C:\Users\Administrator.HP-ENVY-700\.ipfs'
```

**Comment by hacdias** [comment]
It seems that your IPFS repository is corrupted. Please follow the instructions given in https://github.com/ipfs/ipfs-desktop/issues/2037#issuecomment-1074464701 for more information.
