### ISSUE TITLE
[gui error report] HTTPError: could not retrieve links for QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4

### ISSUE THREAD

**Issue by Mlorusso1126** [ipfs/ipfs-desktop#2247]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.22.0
- **Electron Version**: 19.0.8
- **Chrome Version**: 102.0.5005.148

**Error**

```
HTTPError: could not retrieve links for QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc: block was not found locally (offline): ipld: could not find QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc

**Comment by hacdias** [comment]
Please check the README, which has an answer to this: https://github.com/ipfs/ipfs-desktop#i-got-a-network-error-eg-error-fetching-what-should-i-do

Additionally, it clearly says that the content you are trying to find cannot be found locally. You probably do not have an Internet connection or are behind a firewall.
