### ISSUE TITLE
[gui error report] Error: Cannot move 'C:\Users\itali\.ipfs' to a subdirectory of itself, '

### ISSUE THREAD

**Issue by ghost** [ipfs/ipfs-desktop#2262]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.23.0
- **Electron Version**: 19.0.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Cannot move 'C:\Users\itali\.ipfs' to a subdirectory of itself, 'C:\Users\itali\.ipfs\.ipfs'.
    at C:\Users\itali\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\util\stat.js:60:17
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by SgtPooki** [comment]
Thanks for submitting this issue @ghost. Please attach your `error.log` and `combined.log` files so we can investigate further.

See https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files to find your log files
