### ISSUE TITLE
Rename `IPFS-Desktop-[version]-mac.zip` file in Releases?

### ISSUE THREAD

**Issue by tinytb** [ipfs/ipfs-desktop#2291]
**Is your feature request related to a problem? Please describe.**

As noted in https://github.com/ipfs/ipfs-desktop/issues/1922, the "mac.zip" file is used for autoupdate, but should not be downloaded from the GitHub Releases page for installation.

Currently, each Release includes two files that look Mac-related, e.g.:

- IPFS-Desktop-0.24.0-mac.zip
- IPFS-Desktop-0.24.0.dmg

Worse, the `dmg` file doesn't say `mac` in it, so users could be confused if they are not aware that dmg files are only used by Macs, and commonly used for Mac software installation.

**Describe the solution you'd like**

In releases, rename the "mac.zip" file to something that makes it clear that it's not what most users want to download. For example, "IPFS-Desktop-0.24.0-autoupdate-artifact.zip".

**Describe alternatives you've considered**

Renaming "IPFS-Desktop-0.24.0.dmg" may also help. For example, "IPFS-Desktop-0.24.0-mac.dmg". Some Mac users are accustomed to looking for "mac" to find the installer for their platform.

Another idea is to add a note in each release that explains the purpose of each asset. This would reduce confusion for people looking through the list of 17 assets.

**Comment by SgtPooki** [comment]
Triage meeting notes: Need to decide on next action. Can we rename? If not, can we update release description to provide more context for users?

Related:
https://github.com/ipfs/ipfs-desktop/issues/1922
https://www.electron.build/configuration/dmg
https://github.com/electron-userland/electron-builder/pull/6496
