### ISSUE TITLE
Better error handling around repo.lock errors

### ISSUE THREAD

**Issue by whizzzkid** [ipfs/ipfs-desktop#2301]
**Is your feature request related to a problem? Please describe.**
Failing to acquire `repo.lock` errors seem to be common theme in a [few issues filed](https://github.com/ipfs/ipfs-desktop/issues?q=is%3Aissue+repo.lock). This can be handled in a better way.

**Describe the solution you'd like**
A user should not be seeing this error, instead:
- In the short term, we can have a better error message describing what's the issue and how to fix it.
- In the longer term, if there exists a daemon instance that holds the lock, we should broker a connection with that that daemon and use that for operation. In case, the daemon does not exist but a lock file has been left behind, we should delete the lock and spin up a new instance

Since this looks like a frequently occurring issue, handling this would in a better way would be great.

**Comment by SgtPooki** [comment]
1. investigate existing code to see what could be wrong (lidel indicates that ipfs desktop should have code that handles repo.lock issues) 
   * We already prompt users to start IPFS Desktop kubo daemon on different port if we notice that ipfs daemon is already running. If this process fails, we should handle more gracefully

Ultimately, we want to reduce 'repo.lock' errors, while providing users with a quicker solution for unblocking themselves.
