### ISSUE TITLE
Installed on Mac, but tray bar show "IPFS is Starting" forever

### ISSUE THREAD

**Issue by code-brewer** [ipfs/ipfs-desktop#2307]
- OS:  macOS, 
- Version of IPFS Desktop： 0.24.0

**Describe the bug**
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/9084210/197346666-01a71c5c-5ba9-4db9-baf7-75e6c25f98d1.png">

Also, I can not find 'ipfs' command in new-launch terminal when try to run by command line.

I have try re-installation, nothing changed.

**Comment by whizzzkid** [comment]
Thanks for submitting the issue @code-brewer!

>I can not find 'ipfs' command in new-launch terminal when try to run by command line.

Just to clarify, ipfs-desktop does not provide `ipfs` command in the terminal. To have that, you can install ipfs implementation of your choice, using the package manager of your choice.

Regarding the issue that you're facing, can you please attach logs (that can be found [here](https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files)) so we can investigate this further.
