### ISSUE TITLE
Uploading large folder fails when it reach 100%

### ISSUE THREAD

**Issue by 0AAK0** [ipfs/ipfs-desktop#2322]
Hi guys,
file got uploaded but whenever I try to access the CID its gateway timeout, any help? folder is pinned to local node.

regards.

**Comment by whizzzkid** [comment]
Thanks for submitting the issue @0AAK0 can you please share more accurate steps to reproduce this issue? e.g.

- Folder/File size that's considered "large"
- Additional logs from your instance (which can be found [here](https://github.com/ipfs/ipfs-desktop/blob/main/README.md#where-are-my-ipfs-configuration-and-log-files))
- Are other CIDs working as expected?

Thanks

**Comment by 0AAK0** [comment]
> Thanks for submitting the issue @0AAK0 can you please share more accurate steps to reproduce this issue? e.g.
> 
> * Folder/File size that's considered "large"?
> * What OS are your working with?
> * Additional logs from your instance (which can be found [here](https://github.com/ipfs/ipfs-desktop/blob/main/README.md#where-are-my-ipfs-configuration-and-log-files))
> * Are other CIDs working as expected?
> 
> Thanks

Hi, thanks for your reply. issue fixed, I did retry few times and it worked.
another thing to consider is to enough space in your disk as IPFS is converting the upload folder into blocks and copy it inside the same partition "C:\"
