### ISSUE TITLE
[Feature] Collections in the "Files" tab

### ISSUE THREAD

**Issue by danimesq** [ipfs/ipfs-desktop#2328]
Organize files by "folders"/collections.

**Comment by whizzzkid** [comment]
Thanks for submitting this issue @danimesq. Can you please explain more on how do you want to:

> Organize files by "folders"/collections.

Right now, you can create a "New Folder", by clicking the "+Import" -> "New Folder" and can then drag and drop files inside that folder. But I am guessing that's what not you're expecting, what would make this better? If you can annotate a screenshot that would be excellent to have a discussion around, but if not just a list of things that you feel would make this better/intuitive would be nice to have.

Thanks

**Comment by SgtPooki** [comment]
Closing because there is a path forward and we don't have further information.
