### ISSUE TITLE
[gui error report] TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by FranckStone** [ipfs/ipfs-desktop#2398]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 10.0.22621
- **IPFS Desktop Version**: 0.26.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
TypeError: Object has been destroyed
    at run (C:\Program Files\IPFS Desktop\resources\app.asar\src\index.js:100:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SgtPooki** [comment]
@FranckStone Thanks for submitting this issue. It looks like the culprit exists at https://github.com/ipfs/ipfs-desktop/blob/07ee9c2474120d1a8c972be8e379c2d3f974702f/src/index.js#L100

- Can you please provide more details about what you were doing before and during the time when you got this error?
- Was this after an update?
- Can you provide your `error` and `combined` log files? (https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files)

**Comment by FranckStone** [comment]
[error.log](https://github.com/ipfs/ipfs-desktop/files/10785565/error.log)
