### ISSUE TITLE
Release with Kubo 0.18.1 + ensure we aim to ship future Kubo releases within 1 week

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#2407]
https://github.com/ipfs/ipfs-desktop/pull/2396 was merged a week ago, but not released yet.

Ref. https://github.com/ipfs/kubo/blob/master/docs/changelogs/v0.18.md#v0181

**Comment by lidel** [comment]
@galargh  @SgtPooki any thoughts how we can ensure Kubo is shipped with ipfs-desktop within more sane cadence, eg. 1 week window?  Desktop users being stuck on old version is not the best:

- :warning: 0.18.1 (this one) 
   - https://github.com/ipfs/ipfs-desktop/pull/2396  PR merged Jan 27 
   - still not released on Feb 6th (week since merge)
- :warning: 0.18.0 
   - https://github.com/ipfs/ipfs-desktop/pull/2363 PR  merged Jan 27 
   - [released Jan 28](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.26.0)  → 1 day  (but afaik only because GUI team happened to ship metrics  PR the next day)
- :anger:  0.17.0 
  - https://github.com/ipfs/ipfs-desktop/pull/2338 PR merged  Nov 22 
  - [released Dec 11](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.25.0) → **20 days in limbo** 
- :anger:  0.16.0 
  - https://github.com/ipfs/ipfs-desktop/pull/2280 PR merged Oct 10  
  -  [released Nov 11](https://github.com/ipfs/ipfs-desktop/releases/tag/v0.24.1) → **32 days in limbo** 

If GUI team has no bandwidth, perhaps this should it be part of Kubo release checklist, so we  don't forget shipping updates in the future?

**Comment by galargh** [comment]
Before jumping to action, I'd like to understand the root of the problem.

#### Past Releases

1. Who's performing ipfs-desktop releases right now? Is it IPFS GUI team? 
1. Why hasn't it happened in case of past releases? 
1. Is Kubo dependency update PR a good enough prompt for release?

#### Release Process

1. Are https://github.com/ipfs/ipfs-desktop/blob/main/DEVELOPER-NOTES.md up to date?
https://github.com/ipfs/ipfs-desktop/blob/main/DEVELOPER-NOTES.md#manual-testing looks especially burdensome. I'm not too familiar with desktop application testing automation space. Have we ever looked into it?
1. After that, https://github.com/ipfs/ipfs-desktop/blob/main/DEVELOPER-NOTES.md#main-release-process looks pretty standard. I don't see anything https://github.com/ipfs/kuboreleaser isn't already doing so we might be able to easily piggyback off of it. Were there previous efforts to automate this part of the release process?
1. How often is https://github.com/ipfs/ipfs-desktop/blob/main/DEVELOPER-NOTES.md#manually-notarize-dmg-with-apple required?

#### Kubo

1. Are Kubo maintainers best suited to resolve issues that might arise during ipfs-desktop release?

---

My initial thoughts: I'm afraid of integrating ipfs-desktop release process directly into Kubo release process. The latter is already quite complicated. I think that by adding such a sizeable step to it, we'd make ourselves more likely to put off Kubo releases. Personally, I wouldn't do, at the very least, as long as it involves this lengthy manual testing section. Instead, I think we should concentrate on better integration of the two. Making sure that Kubo release initiates ipfs-desktop release process properly.

**Comment by SgtPooki** [comment]
released newest ipfs-desktop: https://github.com/ipfs/ipfs-desktop/releases/tag/v0.26.1

**Comment by BigLep** [comment]
Agreed on not integrating ipfs-desktop release with Kubo release process.

If we take a week SLA as the lag between Kubo and desktop, can Ignite meet that?  What will the team's mechanism be for meeting this?  Automating the ipfs-desktop release would be awesome, but I don't know how possible that is.  Another option would be to make a call to the community.  We could get a couple of people signed up who smoke test the release (following a checklist I provide).  If a couple of them run through the checklist and sign off, we let the PR be merge and desktop release to happen.

**Comment by SgtPooki** [comment]
We could do a week, but we need some kind of consistent notification/hook. For example, if go-ipfs is being updated by the kubo team, then it should be merged by whoever is going to handle the ipfs-desktop release. Doing the go-ipfs merge and then an immediate ipfs-desktop release seems like a reasonable mechanism

**Comment by BigLep** [comment]
If there are changes you want made in the Kubo release process for you are notified, go ahead and leave a comment in https://github.com/ipfs/kubo/pull/9484

**Comment by BigLep** [comment]
There is also this file you can add to be notified of Kubo releases: https://github.com/ipfs/kubo/blob/master/docs/EARLY_TESTERS.md

**Comment by SgtPooki** [comment]
@lidel are you good with the edits to the kubo release notes(https://github.com/ipfs/kubo/pull/9484#discussion_r1117820030)? 

That should be enough to get us on the hook for doing an immediate release after ipfs-desktop PR is opened and tags us.

I'm open to more feedback/recommendations.

**Comment by galargh** [comment]
> @lidel are you good with the edits to the kubo release notes([ipfs/kubo#9484 (comment)](https://github.com/ipfs/kubo/pull/9484#discussion_r1117820030))?
> 
> That should be enough to get us on the hook for doing an immediate release after ipfs-desktop PR is opened and tags us.
> 
> I'm open to more feedback/recommendations.

Can we add CODEOWNERS file in this repo with auto reviewer assignment? In other words, should all the PRs that appear in this repo be reviewed by ipfs-gui-team?

**Comment by SgtPooki** [comment]
@galargh just updated CODEOWNERS to add nishant and myself explicitly: https://github.com/ipfs/ipfs-desktop/commit/11e35c0eb155750cc18d2446cf4a0661e921d11a
