### ISSUE TITLE
[gui error report] Error: migration fs-repo-10-to-11 failed: exit status 1

### ISSUE THREAD

**Issue by Shekelme** [ipfs/ipfs-desktop#2416]
👉️ Please describe what you were doing when this error happened.
I just downloaded the IPFS Desktop program, installed it and launched it. That's all.
**Specifications**

- **OS**: win32 6.1.7601
- **IPFS Desktop Version**: 0.26.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Initializing daemon...
Kubo version: 0.18.0
Repo version: 13
System version: amd64/windows
Golang version: go1.19.1
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 3 migrations, downloading.
Downloading migration: fs-repo-10-to-11...
Downloading migration: fs-repo-11-to-12...
Downloading migration: fs-repo-12-to-13...
Fetching with HTTP: "https://ipfs.io/ipfs/Qmf4yftD4LuMo8JMNPqqw3BtUwYd2VkXMiAThuPE6usrbQ/fs-repo-12-to-13/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/Qmf4yftD4LuMo8JMNPqqw3BtUwYd2VkXMiAThuPE6usrbQ/fs-repo-10-to-11/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/Qmf4yftD4LuMo8JMNPqqw3BtUwYd2VkXMiAThuPE6usrbQ/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/Qmf4yftD4LuMo8JMNPqqw3BtUwYd2VkXMiAThuPE6usrbQ/fs-repo-10-to-11/v1.0.1/fs-repo-10-to-11_v1.0.1_windows-amd64.zip"
Fetching with HTTP: "https://ipfs.io/ipfs/Qmf4yftD4LuMo8JMNPqqw3BtUwYd2VkXMiAThuPE6usrbQ/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip"
Fetching with HTTP: "https://ipfs.io/ipfs/Qmf4yftD4LuMo8JMNPqqw3BtUwYd2VkXMiAThuPE6usrbQ/fs-repo-12-to-13/v1.0.0/fs-repo-12-to-13_v1.0.0_windows-amd64.zip"
Downloaded and unpacked migration: C:\Users\RABINO~1\AppData\Local\Temp\migrations217687659\fs-repo-12-to-13.exe (v1.0.0)
Downloaded and unpacked migration: C:\Users\RABINO~1\AppData\Local\Temp\migrations217687659\fs-repo-11-to-12.exe (v1.0.2)
Downloaded and unpacked migration: C:\Users\RABINO~1\AppData\Local\Temp\migrations217687659\fs-repo-10-to-11.exe (v1.0.1)
Running migration fs-repo-10-to-11 ...
  => Running: C:\Users\RABINO~1\AppData\Local\Temp\migrations217687659\fs-repo-10-to-11.exe -path=C:\Users\rabinovitch\.ipfs -verbose=true
applying 10-to-11 repo migration
opening datastore at "C:\\Users\\rabinovitch\\.ipfs"
upgrading pinning to use datastore
error: failed to transfer pins: failed to convert ipld pin data into datastore
The migrations of fs-repo failed:
  migration fs-repo-10-to-11 failed: exit status 1
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration fs-repo-10-to-11 failed: exit status 1
```

**Comment by Shekelme** [comment]
The only installer that I have stored, in addition to the freshly downloaded `IPFS-Desktop-Setup-0.26.0.exe`, is `IPFS-Desktop-Setup-0.9.7.exe`

**Comment by SgtPooki** [comment]
@Shekelme thanks for submitting this issue.

We use the repo at https://github.com/ipfs/fs-repo-migrations to handle repo migrations, and it seems like the `fs-repo-10-to-11` migration failed because of `failed to convert ipld pin data into datastore`. 

It looks like this is related to https://github.com/ipfs/kubo/issues/7867.

I'll look around a bit more to see if I can find anything helpful

**Comment by SgtPooki** [comment]
@Shekelme it looks like you may be able to fix this by running `ipfs pin add QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn` as specified at https://github.com/ipfs/kubo/issues/7867#issuecomment-897016811

Further discussion in that thread has some helpful tips: 

i.e. summary of the issue by Adin at https://github.com/ipfs/kubo/issues/7867#issuecomment-786107107

**Comment by Shekelme** [comment]
@SgtPooki But how can I do that if my IPFS desktop startup has failed?
![image](https://user-images.githubusercontent.com/26449500/218833371-4a1d9cde-f594-4fe4-84a4-9243256de3a9.png)

**Comment by SgtPooki** [comment]
@Shekelme good point.

Let me look into this and try to get back to you tomorrow

**Comment by SgtPooki** [comment]
If you don't have anything important in there you could just delete the existing ipfs config directory.

I'll have better options for you tomorrow

**Comment by Shekelme** [comment]
> so it's probably safe to delete everything at C:\Users\rabinovitch\.ipfs and try to start ipfs-desktop again.
It looks like it was successfully installed this way.
