### ISSUE TITLE
error: [web ui] render-process-gone: oom, code: -536870904

### ISSUE THREAD

**Issue by Radderz81** [ipfs/ipfs-desktop#2421]
I have updated ipfs-desktop to the latest version, and since then ipfs-desktop seems to disconnect from the deamon. It is running the default inbuilt deamon rather than a custom binary.

I am getting this error in the logs whenever I am pulling large files from one node to another.

2023-02-23T09:46:57.974Z error: [web ui] render-process-gone: oom, code: -536870904

At some point during the download the deamon stops, between a few hundred meg and 2.5GB. The deamon also will not resume the file download, and I have to run a garbage collect before it will reattempt via a new request.

There is a new window in this update showing the deamon running; this remains open with the text still suggesting that it is running, but I'm not sure if this window is still being updated.

To add to the complexity, the node which I am downloading from was also updated, and reinstalled as it was constantly disconnecting after around 5 minutes of inactivity. There was nothing within the log files to suggest why.

**Comment by SgtPooki** [comment]
@Radderz81 I am not sure how this got lost, but I'm truly sorry for the delay in responding to you.

Can you provide an example CID or us to use to attempt to reproduce this error, and the download methods you're using to trigger this error?
