### ISSUE TITLE
IPFS Desktop/WebUI stop loading when turn wifi off

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-desktop#2492]
- OS: macOS
- Version of IPFS Desktop [e.g. 0.20.0]

**Describe the bug**
When I try to load the IPFS Desktop webui when I turn wifi off, the files I have stored on my local IPFS node no longer load (but load fine again when wifi is re-enabled)
<img width="1334" alt="CleanShot 2023-05-25 at 02 42 39@2x" src="https://github.com/ipfs/ipfs-desktop/assets/618519/f3e74505-c1ad-47ed-8510-0f9320926dc7">
- I also briefly saw the "total files" go to -1 B, instead of the correct 17GiB listed here.

**To Reproduce**
1. Go to IPFS Desktop and add some local data
2. Click on files and browse the data
3. Turn off wifi - continue trying to browse the data
4. screen might intermittently go all white, or stop loading files and show the loading screen forever

**Expected behavior**
I should be able to fully browse my local IPFS files even when I'm offline

**Comment by SgtPooki** [comment]
There are some cases where data in MFS is a shallow reference (the bottom of wikipedia mirror wiki references how to do this). 

There are other issues in this repo that have discussed whether we should fully resolve CIDSs locally or not, and that we should provide a UI indicator showing users whether content is actually downloaded or not. 

Self Todo: update this comment with appropriate links

**Comment by SgtPooki** [comment]
I was unable to reproduce this just by disabling wifi. I was able to reproduce this by following the steps in https://github.com/ipfs/ipfs-webui/issues/1691

Steps I followed:

1. Import XKCD archive (CID containing more than a single block) in IPFS-desktop using CID `QmdmQXB2mzChmMeKY47C43LxUdg1NDJ5MWcKMKxDu7RgQm`
2. Note that the file is listed in the Files screen of IPFS-desktop
3. Shut off wifi
4. Note that the files screen never finishes loading


Closing this in favor of https://github.com/ipfs/ipfs-webui/issues/1691 & https://github.com/ipfs/ipfs-webui/issues/961

Other related issues:

* https://github.com/ipfs/ipfs-webui/issues/1248

**Comment by lidel** [comment]
@SgtPooki  another thing one could try here is to check if macOS wifi status is reflected  on [`navigator.onLine` and/or  `addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) APIs.

If so, webui could  register listener to online/offline state change, and modify behavior around items which are not 100% local (e.g. grey them out, set shorter timeout + more meaningful message etc).

Checking what % of data is  local could be expensive, but the result can be cached per CID until the online/offline status changes.

```console
> ipfs files stat --with-local /ipfs/QmTyS43Vbwht5LE8bvPP4nZmWYyc7iafweD6zJhJhGmAJa
QmTyS43Vbwht5LE8bvPP4nZmWYyc7iafweD6zJhJhGmAJa
Size: 0
CumulativeSize: 27932070
ChildBlocks: 29
Type: directory
Local: 980 kB of 28 MB (3.51%)
```

**Comment by SgtPooki** [comment]
@lidel this issue is still closed, because a lot of the work for resolving this will be in ipfs-desktop, but I created https://github.com/ipfs/ipfs-webui/issues/2135 to consolidate work for addressing all of the issues affecting the experience that caused the filing of this issue.

let's continue any further discussion there.
