### ISSUE TITLE
Explore with awesome.ipfs.io

### ISSUE THREAD

**Issue by mainiak** [ipfs/ipfs-desktop#2524]
**Is your feature request related to a problem? Please describe.**
In menu "Explore" (Explore the Merkle Forest), there are four items,
and it seems that IGiS Git repository is dead example.

**Describe the solution you'd like**
1) Removing IGiS until there is a replacement that is actively maintained.
2) Integrate with awesome.ipfs.io to have dynamic content (articles, datasets, videos) people can explore and pin locally.

**Describe alternatives you've considered**
Maybe IPLD format that people could pin on their nodes and share to other people to have sort of bookmarks of content they want to share for explore? (not scope of this request, feel free to ignore)

**Additional context**
Thanks a lot for all this awesome work. This is nice to have request ~ low priority for me.

**Comment by mainiak** [comment]
Note: Some of the items on https://awesome.ipfs.io/ are out of date - ie. Cooking Recepies (QmTXo6GforwsuGAd8behjgvKCsMMBdG1xMZJF4qa9W7CHB) and few others were unreachable (timing out). But "IETF RFC Archive" works just fine and is great example of simple CID inspect & pin use case.

Awesome IPFS categories - `articles`, `datasets`, `videos` - seems like good candidates to show case of content for new users with IPFS (Desktop).

I am not certain about `tools` and `apps` categories (at least in first phase of integration) due to cpu architecture diversity (I guess it would be fine just to download, but ...). I also see potential of making this alternative distribution platform ("application market"?) to Chocolatey and/or Homebrew, etc. But I feel that would seems way out of scope of original ask of fixing Explore section in this ticket.

I am also feeling very conflicted about category `services`, as on one hand, it would/should enable IPFS usage & community to grow, but it is also enabling marketing/advertising, and therefore there __should__ (ideally) be option to opt-out, if that ever happens.

I am also aware that, by implementing integration of IPFS Desktop with awesome.ipfs.io,
there will be also higher maintenance cost - not just on code base of both sides, but possibly on ensuring now content will not shortly disappear - ie. https://github.com/ipfs-inactive/archives/issues/172

Thank you for taking your time reading this and considering any of it. Best regards, -J

**Comment by mainiak** [comment]
Hello @whizzzkid

First, thank you for your response.


One small correction, I did not create any tickets in awesome-ipfs repo, just linked one (can't & won't take credit LOL).

## 1) Re `IGiS Git repo`

It **does show up** and I can pin it in the IPFS Desktop / IPFS Kubo CLI.  
My problem with it, is that [code](https://github.com/ipfs-shipyard/IGiS) seems stale and even the actual [web application](https://igis.io/#/repo/QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY) doesn't work anymore.

I love Git and I really like IPFS, so when I attempted even to clone the repository ... it didn't go well (just tried again):

```
$ git clone ipfs://ipfs/QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY
Cloning into 'QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY'...
panic: walk(/ipfs/QmViWi5az9iiPzESM6ruHf84TcmHSAVQ2KQdNveoDH7eaY/refs) failed: ls: context deadline exceeded

goroutine 1 [running]:
main.main()
        /Users/mainiak/git/projects/git-remote-ipfs/cmd/git-remote-ipfs/main.go:147 +0x604
```
(please ignore above error, I will note it in my code)

So I tried re-create (any) Git repository in IPFS and came up with [this](https://gist.github.com/mainiak/03f202480405affca3fd80dd8f6a7008), which lead me to forking [git-remote-ipfs](https://github.com/mainiak/git-remote-ipfs) (used above).

Spoiler: Yes it works, and you can publish your own repository - but none of the existing tools can be used beyond that (mine included ... so far; let's not dive into this tangent), but it is good enough that **it can be done**.

My point is, IGiS is a **bad example** and doesn't look good. That's it. If it is left there for now, I will not loose sleep over it.

## 2) It's all about being "Awesome"

IGiS aside, I thought that there are plenty good examples in https://awesome.ipfs.io/ and it would be great to expand the "Explore the Merkle Forest" by re-using what already exists - and maybe decoupling the "explore" content from the application code, would allow independent updates (& moderation & curation)

**This is the core of the feature request.** Also market place is somewhat related, but IMHO beyond the scope of integrating with awesome.ipfs.io to show some CIDs.

## 3) Re "IPFS Desktop PRs"

I am honored to be asked, but I apologize, using Electron is rabbit hole I don't really want to go down.

I saw Electron alternative question in https://github.com/ipfs/ipfs-desktop/issues/2184 and might have seriously considered helping if IPFS switched to https://github.com/SgtPooki/ipfs-desktop-wails (also by @SgtPooki!)

"TL;DR" ... Thank you for reading so far and considering this idea.

Best regards, -J

**Comment by SgtPooki** [comment]
@mainiak Thanks so much for your input and suggestions. 

> My point is, IGiS is a bad example and doesn't look good. That's it. If it is left there for now, I will not loose sleep over it.

I just opened https://github.com/ipfs-shipyard/IGiS/issues/86

> plenty good examples in https://awesome.ipfs.io/

We have the examples just listed with a CID at
https://github.com/ipfs/ipld-explorer-components/blob/ca19310defb84611f55c46b1efd399217ba4a8c6/src/components/StartExploringPage.jsx#L35-L59

Feel free to add suggestions for more examples to https://github.com/ipfs/ipld-explorer-components

We don't have the bandwidth for the work to automatically render examples from awesome.ipfs.io. However, adding a simple link to awesome.ipfs.io could be cool so users could find other CIDs to explore. I opened https://github.com/ipfs/ipld-explorer-components/issues/376 for us to discuss further

> Electron alternative

This was also discussed in https://github.com/ipfs/ipfs-desktop/issues/867 where a wails maintainer also offered their help. I previously pinged Kubo/Boxo maintainers about the viability of IPFS-Desktop talking directly to Boxo, and they said it's not quite ready, so for now the idea of a "one process" app isn't ready.

I'm sure some Gophers could create a basic app with wails that starts up the Kubo/boxo daemon, allowing us (and other interested parties) to start contributing. Even if we ran Kubo as a sidecar, or via some `os.exec` command in a wails app, we *should* see a significant increase in ipfs-desktop speed, feature support, and maintainability; assuming wails continues on its great trajectory. 

For now, I'm going to close this, but please continue the conversation at https://github.com/ipfs/ipld-explorer-components/issues/376 if you have ideas on how we should do this or want to submit a PR!
