### ISSUE TITLE
Do not copy files when importing, let the user decide...

### ISSUE THREAD

**Issue by monoflash** [ipfs/ipfs-desktop#2553]
Importing files causes severe redundancy due to a full copy of the files, which in most cases is not needed.

Make an new import mode in which a copy of the files is not created, but a description of where the file is located is created.
You can save in sqlite database:
1. Information about the location of the file.
2. The size, attributes, and checksum of the whole file.

In a separate table, save all the information in chunks of the file. For example:
1. The beginning of a piece of file in bytes.
2. The end of a chunk of the file in bytes.
4. The checksum of a piece of file.

All this can be placed either as it is now in a folder .ipfs or next to the imported file, by analogy as mac OS does (in the file.DS_Store). For example in the file: .ips.data (and inside sqlite) in same folder as imported files.

Let the user decide when importing how to import:
1. Create a copy of the file to the .ipfs folder;
2. Create a link to the file and the .ipfs.data file in the file folder.

The idea is not new, this is how any torrent client behaves, stores all data about the file and file chunks in the [name].torrent file.
This will qualitatively and radically for the better change IPFS and will greatly save space for users using IPFS.

It is also worth adding the ability to export downloaded and user-supported CID files as a file.
This will speed up access to them and also save space.

Support me if someone liked the idea.

**Comment by SgtPooki** [comment]
Thanks for submitting your idea!

This sounds like a protocol change that would be best discussed on discuss.ipfs.tech or in the github.com/ipfs/specs repo.

IPFS-desktop will not be changing the structure of .ipfs folder nor saving any other files it doesnt have to (i.e. the ones electron creates).

If there is a Kubo command that accomplishes what you want, then we could discuss this as a feature enhancement to IPFS-desktop, but I don't believe there is.

Closing as wontfix.
