### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by Goodebags** [ipfs/ipfs-desktop#2554]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 10.0.19045
- **IPFS Desktop Version**: 0.29.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Initializing daemon...
Kubo version: 0.21.0
Repo version: 14
System version: amd64/windows
Golang version: go1.19.10
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-13-to-14...
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/v1.0.0/fs-repo-13-to-14_v1.0.0_windows-amd64.zip"
Downloaded and unpacked migration: C:\Users\User\AppData\Local\Temp\migrations3209015947\fs-repo-13-to-14.exe (v1.0.0)
Running migration fs-repo-13-to-14 ...
  => Running: C:\Users\User\AppData\Local\Temp\migrations3209015947\fs-repo-13-to-14.exe -path=C:\Users\User\.ipfs -verbose=true
The migrations of fs-repo failed:
  migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3209015947\fs-repo-13-to-14.exe: The parameter is incorrect.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations

Error: migration fs-repo-13-to-14 failed: fork/exec C:%5

**Comment by Goodebags** [comment]
IPFS won't load...
Error: migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations3209015947\fs-repo-13-to-14.exe: The parameter is incorrect.

Any help appreciated (although i'm not very at home here)
Thanks

**Comment by Goodebags** [comment]
IPFS node has encountered an error and startup could not be completed:

Initializing daemon...
Kubo version: 0.21.0
Repo version: 14
System version: amd64/windows
Golang version: go1.19.10
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-13-to-14...
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/v1.0.0/fs-repo-13-to-14_v1.0.0_windows-amd64.zip"
Downloaded and unpacked migration: C:\Users\User\AppData\Local\Temp\migrations99369112\fs-repo-13-to-14.exe (v1.0.0)
Running migration fs-repo-13-to-14 ...
  => Running: C:\Users\User\AppData\Local\Temp\migrations99369112\fs-repo-13-to-14.exe -path=C:\Users\User\.ipfs -verbose=true
The migrations of fs-repo failed:
  migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations99369112\fs-repo-13-to-14.exe: The parameter is incorrect.
If you think this is a bug, please file an issue and include this whole log output.
  https://github.com/ipfs/fs-repo-migrations
Error: migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations99369112\fs-repo-13-to-14.exe: The parameter is incorrect.

**Comment by SgtPooki** [comment]
@Goodebags thanks for reporting this error.

It seems like you were running an old version of IPFS-Desktop, and recently attempted to upgrade when you ran into this error. The error messages all say that you're on repo version 14, but if that were true, then the migration should not be running.

Some questions to help us help you better:
1. Can you confirm what you were doing and the exact steps you took prior to receiving this error? 
2. Can you please provide the content of the `version` file listed in your configuration directory? You can find steps to locate the configuration directory at https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files

**Comment by Goodebags** [comment]
Thanks very much for getting back to me :)
As far as I remember, I was just starting up the computer and it didn't want to load,  and so after looking about for a bit and not being very techie at all, I tried to update/re-install it and it made no difference, so tried again for good measure (with all users allowed, not just pc owner(me) and still no difference.
I'm really not very good at clever computer stuff and am struggling to provide this content for you (sorry).
I'm in CMD (as I don't think I can get to the advanced menu in IPFS desktop as won't load up properly) in the IPFS desktop folder, but have just listed the contents and can't see a version file or configuration directory  (again, sorry).

**Comment by Goodebags** [comment]
If you let me know how/what you'd like, I'll do my best.

**Comment by SgtPooki** [comment]
@Goodebags If you just use the File Explorer app, you should be able to find the `version` file in your appdata folder. 

https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/how-to-access-appdata-folder/2194e37a-a36c-443d-8dc0-0b505f5bbb8e has instructions on accessing your appdata folder.  Inside that folder should be an "IPFS Desktop" folder. And inside that folder should be a version file that shows your version.

Please also attach the error.log and combined.log files from that folder so we can investigate further.

If all else fails, and you don't have any previous IPFS data you need to keep, you should be able to completely uninstall the IPFS Desktop application and then install again.

**Comment by Goodebags** [comment]
Thanks and again, apologies as I'm struggling to find a version file.
I'm in IPFS desktop folder in file explorer and there are a bunch of folders, an UPDATERID File, 2 text documents - combined and error, a bunch of JSON files and 2 other files called Local State and Preferences.
I've been using IPFS to store external links for NFTs I've minted and have sold quite a few with links to my IPFS files so am concerned that uninstalling the app would break the links? 
Many thanks for your assistance (and patience with my ignorance)

**Comment by Goodebags** [comment]
[error.log](https://github.com/ipfs/ipfs-desktop/files/12096453/error.log)
[combined.log](https://github.com/ipfs/ipfs-desktop/files/12096454/combined.log)

**Comment by Goodebags** [comment]
Are you able to tell me , please, if this works:
https://docs.ipfs.tech/how-to/move-ipfs-installation/move-ipfs-installation/
or this?
https://discuss.ipfs.tech/t/how-i-can-move-ipfs-client-from-one-pc-to-another-while-retaining-the-peer-id/6868
'simply use old config file. It contains your PeerID and it’s key.
Replace it into new installation folder.
Done'

I'm thinking(hoping) that if I can copy/save the config file elsewhere on my pc, I could uninstall ipfs and then hopefully re-install it and then (somehow) reintroduce/link the old config file and the files previously linked to the local node on this computer will be unaffected.

Do you think this would work?

Ive so far completed these steps:
Stop any IPFS daemons, services, or applications that are currently running.
Open the file explorer and go to C:\Users\YOUR USERNAME, replacing YOUR USERNAME with your current Windows username.
Select the View tab at the top of the file explorer window and check the Hidden items checkbox.
Find the .ipfs within your user's home folder. This is usually C:\Users\YOUR_USERNAME\.ipfs.
Copy this folder to somewhere convenient like the Desktop and rename it to ipfs-backup.

Again, thanks and please excuse my ignorance
best wishes and happy Sunday

**Comment by Goodebags** [comment]
Is it possible to get your help please? I really want to get this fixed and would like to know if I can somehow re-install IPFS and keep the links that are saved onto NFTs that I've minted working? 
I'm not very tech savvy sorry
Many thanks
Rich

**Comment by SgtPooki** [comment]
> I'm thinking(hoping) that if I can copy/save the config file elsewhere on my pc, I could uninstall ipfs and then hopefully re-install it and then (somehow) reintroduce/link the old config file and the files previously linked to the local node on this computer will be unaffected.


If you just replace the config, that won't automatically re-add the files to IPFS. There is a data directory and blockstore that need to go along with it so you should copy the entire `.ipfs` directory like it mentions in that discuss post.


> I really want to get this fixed and would like to know if I can somehow re-install IPFS and keep the links that are saved onto NFTs that I've minted working?

It seems like the quickest fix for you would be to install an older version of IPFS desktop that runs on the correct repo version

if you are on repo version 13, you should use https://github.com/ipfs/ipfs-desktop/releases/tag/v0.28.0
if you are on repo version 14, you should use https://github.com/ipfs/ipfs-desktop/releases/tag/v0.29.0

I hope this helps

**Comment by Goodebags** [comment]
Yes! Thank you! I just re-installed v 13 and it works again. 
Thanks again
