### ISSUE TITLE
[gui error report] Error: Cannot move 'C:\Users\marve\.ipfs' to a subdirectory of itself, '

### ISSUE THREAD

**Issue by NyteWolf22** [ipfs/ipfs-desktop#2561]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 10.0.19045
- **IPFS Desktop Version**: 0.29.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Cannot move 'C:\Users\marve\.ipfs' to a subdirectory of itself, 'C:\Users\marve\.ipfs\.ipfs'.
    at C:\Program Files\IPFS Desktop\resources\app.asar\node_modules\fs-extra\lib\util\stat.js:60:17
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I don't know what I just did.

**Comment by SgtPooki** [comment]
I think this error is fairly reasonable.. closing because the error message is informative enough for users to unblock themselves, and resolving this would require a dance that we shouldn't handle. Also, users can nest content in their OS file manager if desired.
