### ISSUE TITLE
Can't run, Garbage Collector grayed out.

### ISSUE THREAD

**Issue by ZeroCool22** [ipfs/ipfs-desktop#2599]
- OS: Windows 10 x65.
- Version of IPFS Desktop 0.30.1

**Describe the bug**
Garbage Collector option is grayed out.

**To Reproduce**

**Expected behavior**
Be allowed to run it.

**Screenshots**
![Screenshot_18](https://github.com/ipfs/ipfs-desktop/assets/13344308/267bea76-de9c-4ac2-b7e9-b8ba765c4762)

**Comment by SgtPooki** [comment]
@ZeroCool22 @whizzzkid Can you two provide your log files and also confirm whether you have automatic garbage collection enabled or not?

<img width="393" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/1173416/17468e9e-24e6-411f-838a-f7e6f37fefa6">

**Comment by SgtPooki** [comment]
nvm, i don't need it.. we're good. fix coming shortly.
