### ISSUE TITLE
Unable to update IPFS

### ISSUE THREAD

**Issue by Goodebags** [ipfs/ipfs-desktop#2607]
Hi,
I had some trouble recently with my IPFS and had some help from Sgt Pooki.

[SgtPooki](https://github.com/SgtPooki) commented [on Jul 17](https://github.com/ipfs/ipfs-desktop/issues/2554#issuecomment-1638859969)
@Goodebags thanks for reporting this error.

It seems like you were running an old version of IPFS-Desktop, and recently attempted to upgrade when you ran into this error. The error messages all say that you're on repo version 14, but if that were true, then the migration should not be running.
After some 2ing and froing he suggested that I reinstalled an older version to try and fix it and it did (as in I was able to start IPFS up again).
However, since it working, I have attempted to install the suggested update to 0.30.0, but each time, it starts to crash again and I get a very similar error message to what was making it crash the last time and am left with no other option but to re-install the older version 0.28.0 to make it work again. Any help to update would be greatly appreciated.
Many thanks

Rich

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Goodebags** [comment]
Hi Whizzkid and thanks for your reply.
Apologies for the delay in my reply. 
1stly, I was away all of last week camping with family and then I thought I'd replied on the weekend and only just realised I must have not pressed send. Apologies.
I have sold a fw hundred NFTs over the past year and saved a link to my IPFS for many as their external link, so I do want to avoid losing that data.
As IPFS seems to not want me to update it, do you think backing up the data and uninstalling/reinstalling is now my best option?
any help greatly appreciated (and I'm a bit of a muppet at very technical stuff).
Best wishes
Rich

**Comment by Goodebags** [comment]
Something else worth mentioning... If I reinstall v 28, at the end of the installation, when it offers to run IPFS, it works, but if I just start my PC up, it doesn't auto run any more and if I start the IPFS desktop app, it crashes with the same error message...
Hope you have a lovely weekend and thanks again :)

**Comment by SgtPooki** [comment]
to be clear, 

1. the version of ipfs-desktop that works well for you is v0.28.0, correct?
2. the error message you keep running into is `Error: migration fs-repo-13-to-14 failed: fork/exec C:\Users\User\AppData\Local\Temp\migrations99369112\fs-repo-13-to-14.exe: The parameter is incorrect.`, correct?

we probably need to point you over to [fs-repo-migrations](https://github.com/ipfs/fs-repo-migrations) to open an issue, because this repo update process is handled by that binary, and I am honestly out of ideas. I did mention this error in https://github.com/ipfs/fs-repo-migrations/issues/182#issuecomment-1724698461, so you might be able to piggy back there to provide additional relevant info.

**Comment by Goodebags** [comment]
Hi SgtPooki
Yes and yes and thank you.
Best wishes

**Comment by SgtPooki** [comment]
@Goodebags I hope you were able to get unblocked. I'm going to close this issue for now.

---

FYI I recently added some README.md entries with instructions on working around repo-migration errors, but I don't think they will help you with your `fs-repo-13-to-14.exe: The parameter is incorrect.` error.

* https://github.com/ipfs/ipfs-desktop#error-your-programs-version-n-is-lower-than-your-repos-nx
* https://github.com/ipfs/ipfs-desktop#found-outdated-fs-repo-migrations-need-to-be-run---error-fetching-context-deadline-exceeded
