### ISSUE TITLE
How i can block IPFS Update?

### ISSUE THREAD

**Issue by ZeroCool22** [ipfs/ipfs-desktop#2613]
I want to use the **0.29.0** version and not want it to get updated, what file i need to block in the firewall?

**Comment by ZeroCool22** [comment]
Someone?

**Comment by ZeroCool22** [comment]
> Hey @ZeroCool22, apologies for the slow response, I don't think there is a config to prevent automatic update (that can be added, but that would then increase fragmentation of kubo runtimes, which is not ideal)
> 
> That being said, are you comfortable building projects locally? If yes, then I think you can comment out [this line](https://github.com/ipfs/ipfs-desktop/blob/4641dcbeb3c21ffa06412389c39e25865487a085/src/auto-updater/index.js#L192) and build ipfs-desktop locally, that should disable background checks and hence make it stay at the version you'd like.
> 
> Let me know if you need further assistance.

Mmm, i never compiled anything i just use Visual Studio Code for html and css (not JS yet), how i do it?

**Comment by SgtPooki** [comment]
@ZeroCool22 in #2617 you say there are errors that are too big of a problem for you to update. Can you share more information and logs, or relevant existing issues? 

We want to fix all the errors, but without information from users who are experiencing them, we can't address them. 

As far as blocking the auto-update, that is counter-intuitive to deploying fixes that are needed for resolving errors anyone experiences. The right solution is to report the error with as much information as needed so we can address the root problem. 

If we need to hop on a call, let me know, you can email me at my username at protocol.ai, or https://calendly.com/sgtpooki.

**Comment by waltzz92** [comment]
Has any progress been made on this? I too would like a version of IPFS Desktop with automatic updates disabled. As shown by the Windows OS,  its no secret that updates break things. Even worse are bad features being forced on the user by the developer, as is the case with Google's Manifest V3. It would be best if users have full control over the software on their machines.

Unfortunately, I'm not familiar with programming. If someone could make the current Windows version of IPFS Desktop without the update feature, that would be great.

**Comment by SgtPooki** [comment]
@waltzz92 @ZeroCool22 we will add an option in the IPFS-Desktop config.json to disable autoUpdates, but won't provide a UI element for toggling it, so you will be able to disable auto-update, but only via modifying the config.json file.

This will:
1. prevent users who don't know exactly why they're doing it from shooting themselves in the foot (with an easy UI toggle)
2. allow users who are adamant about preventing auto-updates to do what they want
3. be easy to implement (simple config read and wrapper around a few lines in `src/auto-updater/index.js`)

cc @whizzzkid
