### ISSUE TITLE
Garbage Collector problem is not fixed in 0.30.1!

### ISSUE THREAD

**Issue by ZeroCool22** [ipfs/ipfs-desktop#2618]
This still show greyed out:

![Screenshot_2](https://github.com/ipfs/ipfs-desktop/assets/13344308/7be2c417-c090-48f8-ad88-e4e1f0657897)

**Comment by BigLep** [comment]
To be clear, is this saying that what we thought was fixed in https://github.com/ipfs/ipfs-desktop/issues/2599 and https://github.com/ipfs/ipfs-desktop/issues/2595 is still open?

**Comment by ZeroCool22** [comment]
> To be clear, is this saying that what we thought was fixed in #2599 and #2595 is still open?

Correct, https://github.com/ipfs/ipfs-desktop/issues/2599 this one still broke.

**Comment by SgtPooki** [comment]
> Correct, https://github.com/ipfs/ipfs-desktop/issues/2599 this one still broke.

Your screenshot shows that you're on an older version (where translations were still broken) which means you're not on the version where GC fix would be. Please update to the latest and confirm whether you're still experiencing this issue. 

We cannot reproduce.
