### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by ll369** [ipfs/ipfs-desktop#2629]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 10.0.19045
- **IPFS Desktop Version**: 0.30.2
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: Initializing daemon...
Kubo version: 0.22.0
Repo version: 14
System version: amd64/windows
Golang version: go1.19.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 3 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Downloading migration: fs-repo-12-to-13...
Downloading migration: fs-repo-13-to-14...
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-12-to-13/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-12-to-13/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-13-to-14/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmYerugGRCZWA8yQMKDsd9daEVXUR3C5nuw3VXuX1mggHa/fs-repo-12-to-13/versions"

**Comment by SgtPooki** [comment]
@ll369 it looks like some of the output from the kubo daemon was truncated. Can you attach the error & combined log files? you can find them at https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files

**Comment by SgtPooki** [comment]
@ll369 FYI that the repo migration downloads should work properly if given enough time. you shouldn't need to run fs-repo-migrations manually, but you can. 

Before trying fs-repo-migrations manually, see if you can update your IPFS config with the following command:
`ipfs config --json Migration.DownloadSources '["IPFS", "HTTP"]'`

or by changing the json setting in your settings directly via the settings panel in ipfs-desktop:

<img width="489" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/1173416/85d98a16-7e20-480d-9f3b-4ec1b3fb10ac">


Please let us know if you're continuing to experience issues.
