### ISSUE TITLE
bug: auto-update errors

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-desktop#2631]
Some users have reported errors with auto-updating ipfs-desktop.

This issue is intended to track them all and work to resolution.

## related countly errors ([permissioned URL](https://countly.ipfs.tech/dashboard#/5c6ec2b13fd4432348b811a0/crashes))

* [updater] Error: ENOENT: no such file or directory, open '/opt/IPFS Desktop/resources/app-update.yml'

## related issues
* https://github.com/ipfs/ipfs-desktop/issues/2626

**Comment by BigLep** [comment]
I attached my logs: [biglep-2023-09-18-ipfsDesktopLogs.zip](https://github.com/ipfs/ipfs-desktop/files/12653696/biglep-2023-09-18-ipfsDesktopLogs.zip)

**Comment by SgtPooki** [comment]
I didn't see anything obvious in steve's logs.

I just downloaded an old version of IPFS-desktop https://github.com/ipfs/ipfs-desktop/releases/tag/v0.26.1, blocked access to ipfs.io, ran ipfs-desktop v0.26.1, and then selected "check for updates" and it did not update successfully. I am investigating this in addition to https://github.com/ipfs/ipfs-desktop/issues/2632

**Comment by SgtPooki** [comment]
going to download v0.28.0 manually and then try auto-update.

**Comment by SgtPooki** [comment]
v0.28.0 auto update failed. I saw the new app open and then close, and then v0.28.0 re-opened. nothing useful in logs.

**Comment by SgtPooki** [comment]
v0.29.0 manual update also failed. no useful log output other than `2023-09-19T18:48:10.578Z info: [beforeQuitCleanup] stopIpfs had finished with status: 5`

**Comment by SgtPooki** [comment]
manual immediate update also failed for ipfs-desktopv0.30.0, so, i decided to try to "install later" and see if that worked. It did for ipfs-desktopv0.30.0. here are the steps:

1. click "check for updates" in the systray
2. click "install later" on the popup
3. make sure combined.log includes a line saying `2023-09-19T18:53:00.202Z info: [updater] update to 0.30.2 downloaded`
4. quit ipfs-desktop
5. run ipfs-desktop from applications after a few minutes (let electron-updater do it's install stuff during shutdown, ala https://github.com/ipfs/ipfs-desktop/blob/b097be6f06ab1fa325681c67cb9fb67d83e84a2e/src/auto-updater/index.js#L24).

@BigLep can you try this on your version to see if that fixes things?

**Comment by SgtPooki** [comment]
I was also able to successfully update v0.26.1 to v0.30.2 by choosing to "install later". seems like we have a bug with using `quitAndInstall()`, which may also impact auto-update outside of application restarts.

**Comment by BigLep** [comment]
@SgtPooki : earlier this morning I quit IPFS Desktop.  I then just relaunched it, and during the relaunch it appeared to be updating and then I confirmed that I had indeed been updated.  I have attached my [combined.log](https://github.com/ipfs/ipfs-desktop/files/12666166/combined.log).
