### ISSUE TITLE
Google One VPN can't connect, while IPFS is running (Windows)

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#2638]
## System Details

- OS: Windows 11 Home, Version: 22H2
- Version of IPFS Desktop: [v0.30.2](https://github.com/ipfs/ipfs-desktop/releases/v0.30.2)

**Describe the bug**
If the IPFS daemon is stopped, Google One VPN is working fine, but as soon as I start IPFS via the context menu, Google One VPN will disconnect.

I've tried to:

- Disable MDNS discovery
- Change the swarm ports
- Change the Gateway port
- Change the API port
- 
**To Reproduce**
1. Start Google One VPN
2. Start IPFS Desktop
3. Get an error message, that the VPN has disconnected after 5-10 seconds
4. Stop IPFS Desktop
5. Reestablish Google One VPN
6. See it working again
7. Start IPFS Desktop
8. Get an error message, that the VPN has disconnected after 5-10 seconds

**Expected behavior**
I don't think the two programs should interfere with each other. 

**Screenshots**

![Screenshot 2023-09-25 152225](https://github.com/ipfs/ipfs-desktop/assets/614929/a76f8a75-86a6-4b28-a0c7-d6e114d8c39c)

"Connection not possible. Restart VPN to reestablish connection" is the rought translation of the error message.

**Comment by SgtPooki** [comment]
@RubenKelevra thanks for this report.

I don't have Google One so I can't run the VPN (correct me if i'm missing something).

However, I doubt this is something specific to IPFS-Desktop, and more related to Kubo. Could you confirm by running Kubo more directly (outside of IPFS-Desktop) with something like `npx kubo@latest daemon` ?

**Comment by RubenKelevra** [comment]
Yeah you need to subscribe to Google Drive for 2 TB, which unlocks Google's VPN.

Will do asap I'm home.
