### ISSUE TITLE
[gui error report] 

### ISSUE THREAD

**Issue by deenmkkl** [ipfs/ipfs-desktop#2646]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32 10.0.22621
- **IPFS Desktop Version**: 0.30.2
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
Error: EPERM: operation not permitted, rename 'C:\Users\Demzie\.ipfs' -> 'C:\Users\Demzie\METING\.ipfs'
```

**Comment by SgtPooki** [comment]
closing since you have multiple other issues opened with us and we can assume this error was resolved.
