### ISSUE TITLE
Error: To parse non base32 or base58btc encoded CID multibase decoder must be provided

### ISSUE THREAD

**Issue by hadim** [ipfs/ipfs-desktop#2649]
- OS: macOS and Linux
- Version of IPFS Desktop: latest as of today

**Describe the bug**

When trying to access `/ipns/hub.standard-template-construct.org` I get the following error:

```
Error: To parse non base32 or base58btc encoded CID multibase decoder must be provided
```

The Js console error looks similar:

```
Failed to resolve path /ipns/hub.standard-template-construct.org Error: To parse non base32 or base58btc encoded CID multibase decoder must be provided
```

**Comment by hadim** [comment]
Eventually relevant issues:

- https://github.com/multiformats/js-multiformats/issues/90
- https://github.com/MetaMask/metamask-extension/issues/18564

**Comment by SgtPooki** [comment]
@hadim thanks for the report. Can you be more clear about the action you're performing when getting this error?

> When trying to access /ipns/hub.standard-template-construct.org I get the following error:


How are you trying to access it? what IPFS-Desktop view are you on (explore, files, etc..)?

**Comment by hadim** [comment]
I use the top bar to enter the URI.

When clicking on "Browse", I get a 404 error:

![image](https://github.com/ipfs/ipfs-desktop/assets/528003/70844202-b68b-4c4a-9f73-ca43e1b31fbd)

And when clicking on "Inspect", I get the original error reported in this issue:

![image](https://github.com/ipfs/ipfs-desktop/assets/528003/a6f04c95-9f6a-4490-8b4f-8b98a4ce5f81)

**Comment by hadim** [comment]
@SgtPooki do you need more details here?

**Comment by SgtPooki** [comment]
> @SgtPooki do you need more details here?

Sorry for the delay, and thanks for checking in again!

I believe this is enough information, but unfortunately, we still do not support `ipns/` names in the search bar of ipfs-webui/ipfs-desktop (which is handled by https://github.com/ipfs/ipld-explorer-components and can be tested directly at https://explore.ipld.io/#/explore/ipns/docs.ipfs.tech).

We have a tracking issue for this at https://github.com/ipfs/ipld-explorer-components/issues/400. It shouldn't take much to add the support, but we have some higher priority items right now that may delay this work. 

closing in favor of https://github.com/ipfs/ipld-explorer-components/issues/400
