### ISSUE TITLE
Requesting a build of IPFS Desktop from my fork

### ISSUE THREAD

**Issue by waltzz92** [ipfs/ipfs-desktop#2695]
Hello. I made a fork of IPFS Desktop, but I'm not knowledgable/comfortable with building it myself. I'm requesting a Windows build for my repository located here:

https://github.com/waltzz92/ipfs-desktop

**Comment by SgtPooki** [comment]
@waltzz92 We do not provide build services for custom applications or forks. 

You can disable auto updates by going into the [IPFS Desktop config](https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files) and setting `disableAutoUpdate: true` in the `config.json` file in your directory.
