### ISSUE TITLE
[gui error report] SyntaxError: Unexpected end of JSON input: The system cannot find the pa

### ISSUE THREAD

**Issue by mohammedpatla** [ipfs/ipfs-desktop#2731]
👉️ Please describe what you were doing when this error happened.

After install and startup, i might have some cache files from an older installation that are probably breaking something.

**Specifications**

- **OS**: win32 10.0.22631
- **IPFS Desktop Version**: 0.32.0
- **Electron Version**: 19.1.9
- **Chrome Version**: 102.0.5005.167

**Error**

```
SyntaxError: Unexpected end of JSON input: The system cannot find the path specified.
    at JSON.parse (<anonymous>)
    at Daemon._getConfig (C:\Users\<USERNAME>-PC\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:368:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Daemon.init (C:\Users\<USERNAME>-PC\AppData\Local\Programs\IPFS Desktop\resources\app.asar\node_modules\ipfsd-ctl\src\ipfsd-daemon.js:158:9)
    at async getIpfsd (C:\Users\<USERNAME>-PC\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:63:7)
    at async startDaemon (C:\Users\<USERNAME>-PC\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\daemon.js:210:17)
    at async startIpfs (C:\Users\<USERNAME>-PC\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:49:17)
    at async setupDaemon (C:\Users\<USERNAME>-PC\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\daemon\index.js:116:3)
    at async Promise.all (index 1)
    at async run (C:\Users\

**Comment by mohammedpatla** [comment]
@whizzzkid i crosschecked this file does not exist. Like i installed it using the Windows GUI tool, so I'm not sure if this is supposed to be automatically created.

**Comment by mohammedpatla** [comment]
Yea i cant seem to find log files, in the directory's as there is nothing named ipfs.log. the only log i get is the one when i launch

<img width="1345" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/16710191/089751aa-a0a8-48c8-a26f-6516df50770a">

<img width="413" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/16710191/d79ef914-733a-4046-9ef5-dbf4eac66f8e">

**Comment by mohammedpatla** [comment]
Let me know if there is more info and where i can find it?

**Comment by SgtPooki** [comment]
@mohammedpatla 

I am not sure why the config file wasn't created for you on the new run. I'm looking into this now, because we've had this error for a while.

I was able to create a fresh config file via the below code:

```
```

which gave me the following:

```
{
  "Identity": {
    "PeerID": "12D3KooWQq54cuz1sHuerjJsiXAKiNmVuRmmVRdjioGjsrsEvq8h",
    "PrivKey": "CAESQHNnYZBO8UUlztAK2S5Vvj599JxezoVQfwedgRkl/TSe3w2LGNkcF705qvZhvABMgMf+WBF/AyavCcN+aqHptRY="
  },
  "Datastore": {
    "StorageMax": "10GB",
    "StorageGCWatermark": 90,
    "GCPeriod": "1h",
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "HashOnRead": false,
    "BloomFilterSize": 0
  },
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ],
    "Announce": [],
    "AppendAnnounce": [],
    "NoAnnounce": [],
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/8080"
  },
  "Mounts": {
    "IPFS": "/ipfs",
    "IPNS": "/ipns",
    "FuseAllowOther": false
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true
    }
  },
  "Routing": {
    "AcceleratedDHTClient": false,
    "Routers": null,
    "Methods": null
  },
  "Ipns": {
    "RepublishPeriod": "",
    "RecordLifetime": "",
    "ResolveCacheSize": 128
  },
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic-v1/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"
  ],
  "Gateway": {
    "HTTPHeaders": {},
    "RootRedirect": "",
    "PathPrefixes": [],
    "APICommands": [],
    "NoFetch": false,
    "NoDNSLink": false,
    "DeserializedResponses": null,
    "DisableHTMLErrors": null,
    "PublicGateways": null,
    "ExposeRoutingAPI": null
  },
  "API": {
    "HTTPHeaders": {}
  },
  "Swarm": {
    "AddrFilters": null,
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "Transports": {
      "Network": {},
      "Security": {},
      "Multiplexers": {}
    },
    "ConnMgr": {},
    "ResourceMgr": {}
  },
  "AutoNAT": {},
  "Pubsub": {
    "Router": "",
    "DisableSigning": false
  },
  "Peering": {
    "Peers": null
  },
  "DNS": {
    "Resolvers": {}
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Provider": {
    "Strategy": ""
  },
  "Reprovider": {},
  "Experimental": {
    "FilestoreEnabled": false,
    "UrlstoreEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "OptimisticProvide": false,
    "OptimisticProvideJobsPoolSize": 0
  },
  "Plugins": {
    "Plugins": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Internal": {}
}
```

You could save that json to a `~/.ipfs/config` file and try to restart IPFS-Desktop yourself, or run `npx kubo@0.25.0 init` in your terminal yourself to generate your own config.

let me know if you have any trouble.. it might be a while until I get a fix out that will self-heal scenarios like this.

**Comment by mohammedpatla** [comment]
@SgtPooki i further looked at this and i found a config.json file in C:\Users\<My-Username>\AppData\Roaming\IPFS Desktop

The config.json looks like this
```
{
	"ipfsConfig": {
		"type": "go",
		"path": "C:\\Users\\Mohammeds-PC\\.ipfs",
		"flags": [
			"--migrate",
			"--enable-gc",
			"--agent-version-suffix=desktop"
		],
		"keysize": 2048
	},
	"language": "en-US",
	"experiments": {
		"npmOnIpfs": false
	},
	"__internal__": {
		"migrations": {
			"version": "0.32.0"
		}
	},
	"openWebUIAtLaunch": false,
	"ipfsOnPath": true,
	"autoLaunch": true,
	"checkedCorsConfig": true,
	"window": {
		"width": 1260,
		"height": 715
	},
	"daemonConfigRevision": 1,
	"binaryPath": "C:\\Users\\Mohammeds-PC\\Downloads\\ipfs\\ipfs"
}
```

What i am not sure of is if this config file is loaded during launch? It could be as simple as wrong path ~/.ipfs/config does not exist in Windows its either under AppData or under Program Files.

Would you also like me to try replacing the above config with this and try again?

Also is it config or config.json?

**Comment by SgtPooki** [comment]
it seems like a lot of files are missing. I would attempt to remove the application entirely, including all data at `C:\Users\<My-Username>\AppData\Local\Programs\IPFS Desktop` and `$HOME/.ipfs` and re-install

**Comment by SgtPooki** [comment]
the config file at `$HOME/.ipfs/config` does not have a `.json` extension, but it's contents ARE json

**Comment by mohammedpatla** [comment]
> it seems like a lot of files are missing. I would attempt to remove the application entirely, including all data at `C:\Users\<My-Username>\AppData\Local\Programs\IPFS Desktop` and `$HOME/.ipfs` and re-install

Now i am always stuck at
<img width="368" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/16710191/4fd8a4cf-0f72-4197-be88-a2b4a2a67b68">


I tried to even restart my computer after uninstall but some service is blocking the installation i am not sure which?

When i ignore and move this forward then i run into
<img width="371" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/16710191/fb583ae7-c440-42ad-91ce-673cacd468ee">

<img width="365" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/16710191/bb88d95b-f5d7-46df-9110-3627eefd016c">

Where it wont open up anyways.

**Comment by SgtPooki** [comment]
You may need to use the windows task manager to close any running processes.

**Comment by mohammedpatla** [comment]
> You may need to use the windows task manager to close any running processes.

There is none running, though I already checked.

**Comment by SgtPooki** [comment]
your files & install became corrupted somehow. deleting files manually (after making sure IPFS Desktop is not running), and re-installing IPFS-Desktop, is really the only path forward that I can think of in this scenario.

If windows is saying that it's still running, then it probably is. I don't know what else to say.

**Comment by mohammedpatla** [comment]
> your files & install became corrupted somehow. deleting files manually (after making sure IPFS Desktop is not running), and re-installing IPFS-Desktop, is really the only path forward that I can think of in this scenario.
> 
> If windows is saying that it's still running, then it probably is. I don't know what else to say.

So i noticed, when i install in a different directory the above error pops up ( i think its because i am not running installer as admin). If i install in the same directory (local/programs) then i run into the same startup problem. 

But i got it running by doign the following:
- So for some reason the file installation happen in C:\Users\<Username>\AppData\Local\Programs
- But the config file lives in C:\Users\<Username>\AppData\Roaming\IPFS Desktop
- In the config file the config is set as config.json instead of just config and that is the reason the app did not load.
