### ISSUE TITLE
Black X on peers page after using hyperlink from status

### ISSUE THREAD

**Issue by eastoncrafter** [ipfs/ipfs-desktop#2732]
👍

- OS: [e.g. macOS, Windows, Linux]
Windows 11 23H2
- Version of IPFS Desktop
kubo v0.24.0 desktop

**Describe the bug**
When clicking on the "Discovered xxx peers" button in Status, it brings you to a page with an X.
**To Reproduce**
1. Go to status category
2. click on "Discovered xxx peers" hyperlink
3. You are redirected to a page showing peers for a moment, then replaced by an X

**Expected behavior**
Hyperlink works and brings you to the peers page without a black X

**Screenshots**
![Screenshot 2024-01-10 183412](https://github.com/ipfs/ipfs-desktop/assets/74274138/4d3db458-e0b3-4f82-bc70-b4392ac239f1)
![Screenshot 2024-01-10 183425](https://github.com/ipfs/ipfs-desktop/assets/74274138/d9ed4cae-3f12-49e9-8aa8-6dc510a8567d)

**Additional context**
Fixed after restart

[combined.log](https://github.com/ipfs/ipfs-desktop/files/13895550/combined.log)
error.log is empty

**Comment by eastoncrafter** [comment]
I did. I quit the application from the tray, and the same result occurred. Screen recording attached. Sorry for the quality.

https://github.com/ipfs/ipfs-desktop/assets/74274138/99d45a31-b431-47c5-9eea-7867f681f71d

**Comment by eastoncrafter** [comment]
More info was provided in my prior comment. Willing to provide any help possible!

**Comment by SgtPooki** [comment]
@eastoncrafter are you using the latest IPFS desktop version? I solved an error that was populating on this page when I added the new filter input on the peers page, and I don't see that on the screenshot you provided. here is an example of what that would look like

<img width="1527" alt="image" src="https://github.com/ipfs/ipfs-desktop/assets/1173416/81d1cc04-2d6a-44fa-b6c9-7c9ce995b980">
