### ISSUE TITLE
Version 0.37.0 consumes a lot of RAM on Ubuntu-based Linux OS

### ISSUE THREAD

**Issue by heEXDe** [ipfs/ipfs-desktop#2833]
**OS**: Ubuntu-based distribution of Linux
**Version of IPFS Desktop**: 0.37.0 (AppImage)

## Description:
Version 0.37.0 consumes a lot of RAM (sometimes over 5 GB), when connecting with more than 2K peers.

## To reproduce:
1. start the app
2. open the system monitor

**Comment by lidel** [comment]
@heEXDe thank you for filling this. Mind providing bit more context, so we can route this to the right repository?

1. is the memory usage coming mostly from `kubo` daemon or Electron (Desktop app GUI)? 
1. how long is your node running?
1. are you running with default Kubo configuration, or did you adjust things like [`Swarm.ConnMgr`](https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmconnmgr)? The default should trim unused connections down to <100 when idle.

**Comment by heEXDe** [comment]
1. Most of the memory usage seems to come from Kubo itself (screenshot)
![Screenshot_2024-06-27_23-25-57](https://github.com/ipfs/ipfs-desktop/assets/61631314/1cfc0fdb-60d5-4a12-8f6f-94cf4850e600)

2. The node usually operates more than 5 hours a day
3. I don't recall making changes to the default settings. When idle, the node indeed uses much less memory and connects to fewer than 100 peers.
