### ISSUE TITLE
Problem with availability of other folders, files

### ISSUE THREAD

**Issue by ckorodenis** [ipfs/ipfs-desktop#2835]
Version IPFS Desktop 0.37.0 (agent kubo v0.29.0 desktop) Win 64bit

Files and folders are not available on the public gateway. I have tried all the usual procedures. 

I uploaded folder 1, everything is fine, folder is available within 10 seconds until today, folder, files everything works. 

I uploaded folder 2, it is available on local gateway, not available on public. Pinning, publishing to IPNS, changing settings, reinstalling, new configuration, or a few hints from the forum, nothing helped me. 

I have run the test several times, always with the same positive result. I am sending screenshots. 

I tried to re-upload the files several times, no change. 

The files are legitimate *.jpg - max size 1mb - read and write permissions - connection stable - bandwidth sufficient - peers 95~980 - network traffic active without crashes - CID ok 

Does anyone have a solution to the problem? 

![IPFS Check](https://github.com/ipfs/ipfs-desktop/assets/35576615/074046dd-8277-414a-91da-af74ad600a1d)
![pl-diag01](https://github.com/ipfs/ipfs-desktop/assets/35576615/9ed9fa70-8b76-4fb0-bb95-7ffed1d89511)
![pl-diag02](https://github.com/ipfs/ipfs-desktop/assets/35576615/3c085041-4fbb-414c-94e9-7286cc4bb06a)
![pl-diag03](https://github.com/ipfs/ipfs-desktop/assets/35576615/7aaa740e-2627-4a49-82ae-c7b0ffcd57af)
![pl-diag04](https://github.com/ipfs/ipfs-desktop/assets/35576615/e3659d40-fc56-4080-b6d0-7b4428921c65)

**Comment by lidel** [comment]
Hi, this repository is about ipfs-desktop (bugs and features), which seems to do its job, so closing this issue.

HTTP gateway at `ipfs.io` is backed by a separate piece of software ([Rainbow](https://github.com/ipfs/rainbow/)), and these public good HTTP servers are provided as a free utility on best-effort basis: 
- https://docs.ipfs.tech/concepts/public-utilities/#public-ipfs-gateways 

To report any technical problems with these gateways, you can open an issue in the [Waterworks Community repository](https://github.com/ipshipyard/waterworks-community).
