### ISSUE TITLE
🏞 Native OS Integrations Provided by IPFS Desktop

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-desktop#679]
### Summary

This issue is an entry point for gathering prior art, feature requests and ongoing work  around native integrations for the most popular operating systems. 

Comment below if something should be added to the list and/or moved to a dedicated issue.

### Status

|  | Linux/BSD | macOS | Windows |
| ---- | ---- | ---- | ---- | 
| GUI for starting/stopping go-ipfs | 🐓 |🐓 | 🐓 |
| System Tray/Menubar Icon | 🐓 |🐓 | 🐓 |
| [Automatic updates](https://github.com/ipfs-shipyard/ipfs-desktop/issues/668) | 🐥 | 🐓 | 🐓 |
| [System-wide protocol handler](https://github.com/ipfs-shipyard/ipfs-desktop/issues/807)  | 🥚   | 🐓   | 🐓  |
|  [Dropbox-like mounting of MFS](https://github.com/ipfs-shipyard/ipfs-desktop/issues/618) | 🐣    | 🐣   | 🐣  |
| ["Add to IPFS" from Native File Manager](https://github.com/ipfs-shipyard/ipfs-desktop/issues/678)  |  :grey_question:    |  :grey_question:    | 🐓 |
| [Add 'ipfs' to PATH](https://github.com/ipfs-shipyard/ipfs-desktop/issues/727) | 🐓 | 🐓 | 🐓 |

- :grey_question: : Status unknown
- 🥚 : In design phase 
- 🐣 : Work in progress
- 🐥 : Try it out (implementation exists, but requires additional work or setup)
- 🐓 : Shipped (works out of the box when ipfs-desktop is installed)

**Comment by hacdias** [comment]
I believe we should start by "Add to IPFS" from the Native File System. This effort (mainly Windows/macOS) should split around the team members who use which platform.

@olizilla I agree when you said the FUSE-mounting system is the most interesting. It is, but I think that an option to Add to IPFS fro the Native File Browser is simpler now. Although, by mounting it in the OS, the native file manager option gets a bit pointless, no?

What do you think?

/cc @ipfs-shipyard/gui
