### ISSUE TITLE
📦 Stores and Package Managers

### ISSUE THREAD

**Issue by hacdias** [ipfs/ipfs-desktop#691]
### Summary

Many users want to see IPFS Desktop binaries distributed across many stores and package managers. This issue will be used to address those and new requests should be done here for now.

### Status

| Package Manager   | Status | How to |
|-------------------|--------| ---- |
| Homebrew (macOS)  |    🐓   | `brew cask install ipfs` |
| Chocolatey (Windows)       |    🐓  | `choco install ipfs-desktop` |
| Scoop (Windows)|    🐓  |`scoop bucket add extras && scoop install ipfs-desktop` <br>[package](https://github.com/lukesampson/scoop-extras/blob/master/bucket/ipfs-desktop.json) maintained by @NatoBoram |
| WinGet (Windows) | ❔ | |
| PPA Ubuntu/Debian |    ❔    | |
| Flatpak           |    ❔    | |
| Snap              |    🐓    | `snap install ipfs-desktop` |
| AUR				|    🐓    | [package](https://aur.archlinux.org/packages/ipfs-desktop/) maintained by @alexhenrie  |
| App Store (macOS) | ❔ | |

- :grey_question: : Status unknown
- 🐣 : Work in progress
- 🐓 : Published

**Comment by mkg20001** [comment]
I'd also add snaps (snapcraft.io) to the list as it's also a fairly common distribution method and can be easily integrated (build.snapcraft.io)

**Comment by lidel** [comment]
\+ we should provide prebuilt standalone `.deb` and `.rpm` as best-effort approach to remaining Linux distros.

**Comment by hacdias** [comment]
Brew cask just added as `ipfs`. See the [PR](https://github.com/Homebrew/homebrew-cask/pull/60498) for why it is not `ipfs-desktop`. 

`brew cask install ipfs` for everyone.

**Comment by lidel** [comment]
Note that we now [provide](https://github.com/ipfs-shipyard/ipfs-desktop/blob/master/README.md#install) a generic Tar package (`.tar.xz`) for Linux.
It should make packaging for a specific distro easier (no need for manual build).

**Comment by grahamperrin** [comment]
Might someone add and maintain a port for FreeBSD?

We have https://www.freshports.org/sysutils/ipfs-go/ for IPFS implementation in Go, but no port for IPFS Desktop.

**Comment by lukas2005** [comment]
An AUR would be nice :)

**Comment by boomshroom** [comment]
Nixpkgs, or just a nix file in the repo. 1 complication for this is the difficulty in setting up an Electron package at the moment. The unorthodox directory structure makes it difficult build normally.

**Comment by NatoBoram** [comment]
It's available via [`scoop`](https://github.com/lukesampson/scoop) [here](https://github.com/lukesampson/scoop-extras/blob/master/bucket/ipfs-desktop.json).

```pwsh
scoop install ipfs-desktop
```

**Comment by Dr-Chronosphere** [comment]
Could someone add WinGet to the list of package managers? It's still in active development, but I feel like Microsoft is going to make a larger push for it in the future.

**Comment by prototype99** [comment]
I cannot find support Gentoo (portage) yet.

**Comment by lidel** [comment]
@agnelvishal definitely, but we need to migrate autoupdate mechanizm to support that first – see my notes in https://github.com/ipfs-shipyard/ipfs-desktop/issues/1263#issuecomment-558416578

**Comment by RubenKelevra** [comment]
Flatpak would be nice!

**Comment by NatoBoram** [comment]
Looks like I was completely ignored even thought `winget` was added to the list. Here's a reminder that I commented.

> It's available via [`scoop`](https://github.com/lukesampson/scoop) [here](https://github.com/lukesampson/scoop-extras/blob/master/bucket/ipfs-desktop.json).
> 
> [lukesampson/scoop-extras#1597](https://github.com/lukesampson/scoop-extras/issues/1597)
> 
> ```powershell
> scoop bucket add extras
> scoop install ipfs-desktop
> ```

It's important to not discriminate package managers. If this issue is not taken seriously, then please consider closing it.

**Comment by hacdias** [comment]
@NatoBoram added to the list!

**Comment by jessicaschilling** [comment]
@NatoBoram - note that Scoop has been listed in the docs at https://docs.ipfs.io/install/ipfs-desktop/#package-managers for a while now. Will update CLI instructions per your comment under https://github.com/ipfs/ipfs-docs/pull/615.

**Comment by FireMasterK** [comment]
There seems to be a package fro WinGet now: https://winget.run/pkg/IPFS/IPFS-Desktop

**Comment by ShadSterling** [comment]
Macports (macOS) has an ipfs package: https://ports.macports.org/port/ipfs/summary

I'm guessing it's just the CLI (not the Desktop), but should be on the list

**Comment by lidel** [comment]
I'm closing this and suggest that people just open a PR against ["Install" section of README](https://github.com/ipfs/ipfs-desktop#install) so it can be discovered by others with more ease :)

**Comment by ShadSterling** [comment]
Added MacPorts in PR #1816

WinGet is still missing; I haven't used Windows since XP, so I'll leave that for someone more familiar.
Maybe @FireMasterK ?

**Comment by lessneek** [comment]
why there is no a Flatpak package? any plans?

**Comment by KaKi87** [comment]
Hello,
Why was this closed ?
There's currently no package manager support whatsoever for Debian-based distros (APT/PPA/Flatpak/Snap).
Thanks

**Comment by DeedleFake** [comment]
I currently use the AppImage on Manjaro and it is very, very much a less than ideal experience. Trying to get it to consistently autostart when I login seems to be impossible. A Flatpak would be very much appreciated.

**Comment by KaKi87** [comment]
Hi,

A few months ago, I started developing a tool named [dynapt](https://git.kaki87.net/KaKi87/dynapt) to automatically fetch updates through APT for packages that don't provide an APT repository.

As I've been upgrading IPFS Desktop through it for quite some time now, I just published my first pre-release of it, which you can download and set up from [this tutorial](https://gist.github.com/KaKi87/f620788e9901abbfef4978eb7ad358b4).

For IPFS Desktop specifically, replace the following configuration line :

```json
    "apps": []
```

With the following :

```json
    "apps": [
        {
            "name": "IPFS Desktop",
            "github": {
                "repo": "ipfs/ipfs-desktop"
            }
        }
    ]
```

For questions or issues, please submit a comment on the tutorial page.

Thanks

**Comment by omnicortex** [comment]
+1
