### ISSUE TITLE
Menubar icon disappears after 'turning off' IPFS

### ISSUE THREAD

**Issue by meiqimichelle** [ipfs/ipfs-desktop#764]
I would have expected that there is a greyed-out menubar item that I could go to to fire up IPFS again, especially since the icon used in the interface is a "power button". Not sure if this is a bug, or expected behavior at the moment.

**Comment by hacdias** [comment]
Hey @meiqimichelle 😄 Right now, that's the expected behaviour. I wonder: why do you expect it to be greyed out instead of closing the app?

**Comment by meiqimichelle** [comment]
Because all the other menubar apps I have do that /shrug -- I consider them all a 'quick launch' for that service.

**Comment by meiqimichelle** [comment]
More detail...I *can* also quit all of them, but that is one of the options in the drop-down that always hangs around up there -- I have to do something extra to make it disappear from the menubar. So, in this case, if this is how I'm supposed to 'turn IPFS on and off', it seems like it would be much more convenient to access that from the menubar at any point. Otherwise, why *is* it a menubar app, and not just a normal app like any other?

**Comment by fsdiogo** [comment]
I agree with @meiqimichelle, that is the expected behaviour of menu bar apps in macOS.

**Comment by hacdias** [comment]
I also agree, that's how we worked previously.

Just a question: how do you exit a menubar app on macOS? Is there a right click menu?

**Comment by fsdiogo** [comment]
Yes, there is a right-click:

![menu](https://user-images.githubusercontent.com/33324750/50636329-93517b80-0f4d-11e9-9f06-7901a7ad5a3d.gif)

**Comment by hacdias** [comment]
@fsdiogo I think we can do that! It usually works the same way on Windows so I think it's a good bet

**Comment by fsdiogo** [comment]
Agreed 👌
